//
//  PenSupport+GroupFlow.swift
//  Generated by Woodcase. Do not edit.
//
//  Pen's group in a stack. A group has no box of its own: its children sit at their x/y from
//  its anchor, and its box is their union, wherever that starts. In a stack Pen gives the
//  group a slot the size of that union — turned, when the group turns — and draws the union
//  centered in it.
//

import SwiftUI

/// Lays a group's children out at `offsets` from the group's anchor, and sizes to their union,
/// turned by `rotation` when the group turns.
///
/// The union is centered in the bounds the group is placed at, so a `rotationEffect` about the
/// center turns it about the same point Pen does. Each child's own turn does not grow the
/// union here, as its turned bounds do in Pen's layout.
struct PenGroupFlow: Layout {
    /// Each child's `x`/`y` from the group's anchor, in the order the children are listed.
    var offsets: [CGPoint]

    /// The group's turn, in Pen's counter-clockwise degrees; only its size depends on it.
    var rotation: Double = 0

    func sizeThatFits(proposal _: ProposedViewSize, subviews: Subviews, cache _: inout ()) -> CGSize {
        let box = union(of: subviews)
        let radians = rotation * .pi / 180
        let cosine = abs(cos(radians))
        let sine = abs(sin(radians))
        return CGSize(
            width: box.width * cosine + box.height * sine,
            height: box.width * sine + box.height * cosine
        )
    }

    func placeSubviews(in bounds: CGRect, proposal _: ProposedViewSize, subviews: Subviews, cache _: inout ()) {
        let box = union(of: subviews)
        let anchorX = bounds.midX - box.width / 2 - box.minX
        let anchorY = bounds.midY - box.height / 2 - box.minY
        for index in subviews.indices {
            let offset = index < offsets.count ? offsets[index] : .zero
            subviews[index].place(
                at: CGPoint(x: anchorX + offset.x, y: anchorY + offset.y), anchor: .topLeading, proposal: .unspecified
            )
        }
    }

    /// The children's union, measured from the anchor.
    private func union(of subviews: Subviews) -> CGRect {
        var box: CGRect?
        for index in subviews.indices {
            let offset = index < offsets.count ? offsets[index] : .zero
            let child = CGRect(origin: offset, size: subviews[index].sizeThatFits(.unspecified))
            box = box.map { $0.union(child) } ?? child
        }
        return box ?? .zero
    }
}
