//
//  PenSupport+Stroke.swift
//  Generated by Woodcase. Do not edit.
//
//  Pen's strokes. A centred stroke of one paint is SwiftUI's own `stroke`, and an inside
//  one on a rectangle is `strokeBorder`; these shapes draw the rest. Each is the region the
//  stroke covers, so it is painted like a fill — `.fill(style)`, `.background(style, in:)`
//  — and a paint is laid out over the node's box, not over the stroke's own bounds.
//

import SwiftUI

/// Where a stroke sits on its shape's outline.
enum PenStrokeAlignment {
    /// Entirely inside the outline.
    case inside

    /// Centred on the outline.
    case center

    /// Entirely outside the outline.
    case outside
}

extension Shape {
    /// The region a stroke of `lineWidth` covers, placed on the outline by `alignment`.
    func penStroke(_ alignment: PenStrokeAlignment, lineWidth: CGFloat) -> PenStrokeRegion<Self> {
        PenStrokeRegion(shape: self, alignment: alignment, style: StrokeStyle(lineWidth: lineWidth))
    }

    /// The region a stroke of `style` covers, placed on the outline by `alignment`.
    func penStroke(_ alignment: PenStrokeAlignment, style: StrokeStyle) -> PenStrokeRegion<Self> {
        PenStrokeRegion(shape: self, alignment: alignment, style: style)
    }
}

/// The region a stroke covers.
///
/// Centred, it is the stroked outline. Inside and outside, it is the outline stroked at
/// twice the width and cut to the shape or to its complement — an offset of the outline
/// itself, which `strokeBorder`'s inset shape is not for an ellipse or a path.
struct PenStrokeRegion<S: Shape>: Shape {
    /// The shape whose outline is stroked.
    var shape: S

    /// Where the stroke sits on the outline.
    var alignment: PenStrokeAlignment

    /// The stroke's width, caps and joins.
    var style: StrokeStyle

    func path(in rect: CGRect) -> Path {
        let outline = shape.path(in: rect)
        guard alignment != .center else { return outline.strokedPath(style) }
        var doubled = style
        doubled.lineWidth *= 2
        let band = outline.strokedPath(doubled)
        return alignment == .inside ? band.intersection(outline) : band.subtracting(outline)
    }
}

/// A box's stroke with a width per side, as Pen draws it: an outer rounded rectangle less
/// an inner one.
///
/// With `k` the alignment's share outside the box — inside 0, centre ½, outside 1 — each
/// side's band runs from `k·width` outside the box's edge to `(1 − k)·width` inside it. A
/// rounded corner of radius `r` keeps elliptical inner radii `max(0, r − (1 − k)·w)`, `w`
/// being the width of the side each axis crosses, and a circular outer radius `r + k·m`,
/// `m` the smaller adjacent width — except that a centred stroke whose half-width exceeds
/// `r` rounds its outside by that half-width instead.
struct PenSideStroke: Shape {
    /// The width of each side.
    var widths: EdgeInsets

    /// Where the stroke sits on the box's edge.
    var alignment: PenStrokeAlignment

    /// The box's corner radii.
    var cornerRadii: RectangleCornerRadii

    /// A stroke of `widths` on a box with `cornerRadii`.
    init(_ widths: EdgeInsets, alignment: PenStrokeAlignment, cornerRadii: RectangleCornerRadii = RectangleCornerRadii()) {
        self.widths = widths
        self.alignment = alignment
        self.cornerRadii = cornerRadii
    }

    func path(in rect: CGRect) -> Path {
        let k: CGFloat = switch alignment {
        case .inside: 0
        case .center: 0.5
        case .outside: 1
        }
        let (top, left, bottom, right) = (widths.top, widths.leading, widths.bottom, widths.trailing)
        let limit = min(rect.width, rect.height) / 2
        // Clockwise from the top left, with the widths each corner's x and y axes cross.
        let corners: [(r: CGFloat, x: CGFloat, y: CGFloat)] = [
            (min(cornerRadii.topLeading, limit), left, top),
            (min(cornerRadii.topTrailing, limit), right, top),
            (min(cornerRadii.bottomTrailing, limit), right, bottom),
            (min(cornerRadii.bottomLeading, limit), left, bottom),
        ]
        let outerRect = CGRect(
            x: rect.minX - k * left, y: rect.minY - k * top,
            width: rect.width + k * (left + right), height: rect.height + k * (top + bottom)
        )
        let outerRadii: [CGSize] = corners.map { corner in
            guard corner.r > 0 else { return .zero }
            let m = min(corner.x, corner.y)
            let radius = alignment == .center && corner.r < k * m ? k * m : corner.r + k * m
            return CGSize(width: radius, height: radius)
        }
        let outer = Self.roundedRect(outerRect, radii: outerRadii)

        let inset = 1 - k
        // Checked before the rect is built: `CGRect.width` is the standardized, absolute
        // width, so a band wider than the box would come back as a hole cut out of it.
        let innerWidth = rect.width - inset * (left + right)
        let innerHeight = rect.height - inset * (top + bottom)
        guard innerWidth > 0, innerHeight > 0 else { return outer }
        let innerRect = CGRect(
            x: rect.minX + inset * left, y: rect.minY + inset * top, width: innerWidth, height: innerHeight
        )
        let innerRadii: [CGSize] = corners.map { corner in
            guard corner.r > 0 else { return .zero }
            return CGSize(width: max(0, corner.r - inset * corner.x), height: max(0, corner.r - inset * corner.y))
        }
        return outer.subtracting(Self.roundedRect(innerRect, radii: innerRadii))
    }

    /// A rectangle with elliptical corners, top left first and clockwise, each clamped to
    /// half the rectangle; each quarter ellipse is one cubic Bézier.
    private static func roundedRect(_ rect: CGRect, radii: [CGSize]) -> Path {
        let r = radii.map { CGSize(width: min($0.width, rect.width / 2), height: min($0.height, rect.height / 2)) }
        let kappa: CGFloat = 0.552_284_749_8
        let (tl, tr, br, bl) = (r[0], r[1], r[2], r[3])
        var path = Path()
        path.move(to: CGPoint(x: rect.minX + tl.width, y: rect.minY))
        path.addLine(to: CGPoint(x: rect.maxX - tr.width, y: rect.minY))
        path.addCurve(
            to: CGPoint(x: rect.maxX, y: rect.minY + tr.height),
            control1: CGPoint(x: rect.maxX - tr.width * (1 - kappa), y: rect.minY),
            control2: CGPoint(x: rect.maxX, y: rect.minY + tr.height * (1 - kappa))
        )
        path.addLine(to: CGPoint(x: rect.maxX, y: rect.maxY - br.height))
        path.addCurve(
            to: CGPoint(x: rect.maxX - br.width, y: rect.maxY),
            control1: CGPoint(x: rect.maxX, y: rect.maxY - br.height * (1 - kappa)),
            control2: CGPoint(x: rect.maxX - br.width * (1 - kappa), y: rect.maxY)
        )
        path.addLine(to: CGPoint(x: rect.minX + bl.width, y: rect.maxY))
        path.addCurve(
            to: CGPoint(x: rect.minX, y: rect.maxY - bl.height),
            control1: CGPoint(x: rect.minX + bl.width * (1 - kappa), y: rect.maxY),
            control2: CGPoint(x: rect.minX, y: rect.maxY - bl.height * (1 - kappa))
        )
        path.addLine(to: CGPoint(x: rect.minX, y: rect.minY + tl.height))
        path.addCurve(
            to: CGPoint(x: rect.minX + tl.width, y: rect.minY),
            control1: CGPoint(x: rect.minX, y: rect.minY + tl.height * (1 - kappa)),
            control2: CGPoint(x: rect.minX + tl.width * (1 - kappa), y: rect.minY)
        )
        path.closeSubpath()
        return path
    }
}
