//
//  PenSupport+Shape.swift
//  Generated by Woodcase. Do not edit.
//
//  Shapes beyond SwiftUI's own. The pages declare one `Shape` per path, polygon, line or
//  arc, drawn at the node's size and fitted here to the box it is given; an icon is its
//  glyph's outline, read from the icon font the package bundles.
//

import CoreText
import SwiftUI

extension Path {
    /// This path, drawn in a box of `size` at the origin, stretched to fill `rect`. An axis
    /// of zero size — a horizontal or vertical line — is moved but not stretched.
    func penFitted(from size: CGSize, to rect: CGRect) -> Path {
        let scaleX = size.width > 0 ? rect.width / size.width : 1
        let scaleY = size.height > 0 ? rect.height / size.height : 1
        return applying(CGAffineTransform(translationX: rect.minX, y: rect.minY).scaledBy(x: scaleX, y: scaleY))
    }
}

extension Shape {
    /// This shape drawn `dx` and `dy` points inside the box it is offered on each side.
    ///
    /// SwiftUI draws nothing for a view under a point on either axis, stroke and overlay
    /// included, so a line of no height is stroked in a box `.padding` makes taller by its
    /// stroke's reach, with the line drawn back where its own box would be.
    func penOutset(dx: CGFloat, dy: CGFloat) -> PenOutsetShape<Self> {
        PenOutsetShape(shape: self, dx: dx, dy: dy)
    }
}

/// A shape drawn inset in the box it is offered; see ``Shape/penOutset(dx:dy:)``.
struct PenOutsetShape<S: Shape>: Shape {
    /// The shape drawn.
    var shape: S

    /// How far inside the box's left and right edges the shape's own box is.
    var dx: CGFloat

    /// How far inside the box's top and bottom edges the shape's own box is.
    var dy: CGFloat

    func path(in rect: CGRect) -> Path {
        shape.path(in: rect.insetBy(dx: dx, dy: dy))
    }
}

/// An icon: one glyph of a bundled icon font, as large as the box's shorter side, placed
/// where Pen places it — by the font's metrics, not the glyph's ink: its advance centered
/// across the box, and its line box (ascent plus descent, each rounded to a whole point at
/// 14 pt, then scaled) centered down it.
///
/// A shape rather than `Text`, so the icon is painted like any shape: a color, a gradient
/// laid out over the node's box, a stack.
struct PenIconShape: Shape {
    /// The font file, one of the package's bundled fonts (`PenFonts`).
    var file: String

    /// The glyph's code point.
    var glyph: UInt32

    /// The weight axis's value, for a variable font; `nil` keeps the font's default.
    var weight: CGFloat?

    /// The text size at which Pen rounds the font's ascent and descent to whole points.
    static let metricsSize: CGFloat = 14

    /// Glyph `glyph` of the bundled font `file`, at `weight` when the font has the axis.
    init(file: String, glyph: UInt32, weight: CGFloat? = nil) {
        self.file = file
        self.glyph = glyph
        self.weight = weight
    }

    func path(in rect: CGRect) -> Path {
        let size = min(rect.width, rect.height)
        guard size > 0, let scalar = Unicode.Scalar(glyph),
              let font = PenFonts.font(file: file, size: size, weight: weight)
        else { return Path() }
        let characters = Array(String(Character(scalar)).utf16)
        var glyphs = [CGGlyph](repeating: 0, count: characters.count)
        guard CTFontGetGlyphsForCharacters(font, characters, &glyphs, characters.count),
              let outline = CTFontCreatePathForGlyph(font, glyphs[0], nil)
        else { return Path() }
        var advance = CGSize(width: size, height: 0)
        CTFontGetAdvancesForGlyphs(font, .horizontal, glyphs, &advance, 1)
        let ascent = (CTFontGetAscent(font) * Self.metricsSize / size).rounded()
        let descent = (CTFontGetDescent(font) * Self.metricsSize / size).rounded()
        let baseline = rect.midY + size * (ascent - descent) / (2 * Self.metricsSize)
        // Core Text draws y up: flip the outline about its baseline.
        let placement = CGAffineTransform(translationX: rect.midX - advance.width / 2, y: baseline).scaledBy(x: 1, y: -1)
        return Path(outline).applying(placement)
    }
}
