//
//  PenSupport+Fonts.swift
//  Generated by Woodcase. Do not edit.
//
//  The fonts the package bundles — the document's text families and its icon libraries —
//  registered with Core Text from their files in the module's bundle. The views register
//  them on first use, so nothing has to be called before they draw.
//

import CoreText
import Foundation

/// The fonts this package bundles, registered with Core Text for this process.
///
/// Every font file in `Resources/` is registered from its file URL the first time a view
/// sets text or draws an icon, or the first time anything reads ``faces``. An app calls
/// ``register()`` only to name a bundled family in views of its own
/// (`Font.custom("Inter", size: 17)`) before any of this package's views has drawn.
public enum PenFonts {
    /// One bundled font file.
    public struct Face: Hashable, Sendable {
        /// The file's name in the bundle, `Inter[opsz,wght].ttf`.
        public let file: String

        /// The family its first face belongs to, `Inter`.
        public let family: String

        /// Its first face's PostScript name, which Core Text finds it by.
        public let postScriptName: String

        /// Whether Core Text took it: registered now, or already registered.
        public let isRegistered: Bool
    }

    /// Every font file the package bundles, in file-name order, each registered the first
    /// time this is read.
    public static let faces: [Face] = {
        let extensions = ["ttf", "otf", "ttc"]
        let urls = extensions.flatMap { Bundle.module.urls(forResourcesWithExtension: $0, subdirectory: nil) ?? [] }
        return urls.sorted { $0.lastPathComponent < $1.lastPathComponent }.compactMap(face(at:))
    }()

    /// Registers every font the package bundles, once; later calls do nothing.
    public static func register() {
        _ = faces
    }

    /// The bundled font `file` at `size` and, when the font has a weight axis, `weight`;
    /// `nil` when the package does not bundle the file.
    static func font(file: String, size: CGFloat, weight: CGFloat?) -> CTFont? {
        guard let face = faces.first(where: { $0.file == file }) else { return nil }
        let font = CTFontCreateWithName(face.postScriptName as CFString, size, nil)
        guard let weight else { return font }
        // Optical sizing off: Core Text would move an `opsz` axis to the point size, where
        // Pen draws an icon at the font's default optical size.
        let variation = CTFontDescriptorCreateWithAttributes(
            [kCTFontVariationAttribute: [weightAxis: weight], kCTFontOpticalSizeAttribute: "none"] as CFDictionary
        )
        return CTFontCreateCopyWithAttributes(font, size, nil, variation)
    }

    /// The OpenType tag of the weight axis, `wght`.
    private static let weightAxis = 0x7767_6874

    /// Registers the font file at `url` — from the file, because Core Text silently
    /// refuses a font registered from bytes in memory — and describes it; `nil` when it
    /// is not a font.
    private static func face(at url: URL) -> Face? {
        guard let descriptors = CTFontManagerCreateFontDescriptorsFromURL(url as CFURL) as? [CTFontDescriptor],
              let first = descriptors.first,
              let name = CTFontDescriptorCopyAttribute(first, kCTFontNameAttribute) as? String
        else { return nil }
        let family = CTFontDescriptorCopyAttribute(first, kCTFontFamilyNameAttribute) as? String ?? name
        var error: Unmanaged<CFError>?
        var registered = CTFontManagerRegisterFontsForURL(url as CFURL, .process, &error)
        if !registered, let code = (error?.takeRetainedValue()).map(CFErrorGetCode) {
            // Already registered, or a face of that name already is: either way it draws.
            registered = code == CTFontManagerError.alreadyRegistered.rawValue
                || code == CTFontManagerError.duplicatedName.rawValue
        }
        return Face(file: url.lastPathComponent, family: family, postScriptName: name, isRegistered: registered)
    }
}
