//
//  PenSupport+Paint.swift
//  Generated by Woodcase. Do not edit.
//
//  Paints SwiftUI cannot say on its own: a gradient laid out the way Pen lays it out, a
//  stack of paints shown through a text's glyphs, and an image loaded from a bundled file.
//

import SwiftUI
#if canImport(UIKit)
    import UIKit
#else
    import AppKit
#endif

/// A Pen gradient, drawn through Pen's own map from the gradient's unit space into the box.
///
/// In its own space a gradient is centred on the origin with unit extent (y down): a linear
/// one runs from stop 0 at `(0, 0.5)` to stop 1 at `(0, -0.5)`; a radial one from the origin
/// to the circle of radius ½; an angular one starts pointing up and sweeps clockwise. That
/// space is scaled by `width` and `height`, turned counter-clockwise by `rotation` degrees,
/// moved to `center`, and only then stretched to the box — so on an oblong box a turned
/// gradient does not keep its angle, and a radial or angular one becomes an ellipse. The
/// generated views use SwiftUI's `.linearGradient`, `.ellipticalGradient` and
/// `.conicGradient` wherever those draw the same thing, and this view elsewhere.
struct PenGradient: View {
    /// The gradient's shape.
    enum Kind {
        case linear, radial, angular
    }

    /// Linear, radial or angular.
    var kind: Kind
    /// The stops, in the colour space they interpolate in.
    var gradient: AnyGradient
    /// The gradient's centre in the box.
    var center: UnitPoint
    /// The scale along the gradient's own x axis.
    var width: CGFloat
    /// The scale along the gradient's own y axis.
    var height: CGFloat
    /// The turn, in degrees counter-clockwise.
    var rotation: Double

    init(
        _ kind: Kind,
        _ gradient: AnyGradient,
        center: UnitPoint = .center,
        width: CGFloat = 1,
        height: CGFloat = 1,
        rotation: Double = 0
    ) {
        self.kind = kind
        self.gradient = gradient
        self.center = center
        self.width = width
        self.height = height
        self.rotation = rotation
    }

    /// How far past its box the gradient is drawn: a stroke outside the box needs it.
    @Environment(\.penPaintBleed) private var bleed

    var body: some View {
        let bleed = bleed
        Canvas { context, size in
            // The canvas is the box grown by `bleed` on every side; the gradient is laid out
            // over the box, and padded beyond it as Pen pads it.
            let box = CGSize(width: size.width - 2 * bleed, height: size.height - 2 * bleed)
            let map = CGAffineTransform(scaleX: width, y: height)
                .concatenating(CGAffineTransform(rotationAngle: -rotation * .pi / 180))
                .concatenating(CGAffineTransform(translationX: center.x, y: center.y))
                .concatenating(CGAffineTransform(scaleX: box.width, y: box.height))
                .concatenating(CGAffineTransform(translationX: bleed, y: bleed))
            // A zero size or an empty box collapses the gradient: nothing to draw.
            guard abs(map.a * map.d - map.b * map.c) > 1e-12 else { return }
            let area = Path(CGRect(origin: .zero, size: size)).applying(map.inverted())
            context.concatenate(map)
            let shading: GraphicsContext.Shading = switch kind {
            case .linear:
                .linearGradient(gradient, startPoint: CGPoint(x: 0, y: 0.5), endPoint: CGPoint(x: 0, y: -0.5))
            case .radial:
                .radialGradient(gradient, center: .zero, startRadius: 0, endRadius: 0.5)
            case .angular:
                .conicGradient(gradient, center: .zero, angle: .degrees(-90))
            }
            context.fill(area, with: shading)
        }
        .padding(-bleed)
    }
}

extension EnvironmentValues {
    /// How far past its box a `PenGradient` below is drawn, in points.
    @Entry var penPaintBleed: CGFloat = 0
}

extension View {
    /// Draws every `PenGradient` in this view `amount` points past its box on each side,
    /// for a stroke that reaches outside the node: Pen lays a stroke's paint out over the
    /// node's box and pads a gradient beyond it. An image is not drawn past its place.
    func penPaintBleed(_ amount: CGFloat) -> some View {
        environment(\.penPaintBleed, amount)
    }
}

public extension Image {
    /// The image file `file` (`photo.png`) in `bundle` — the package's `Bundle.module`,
    /// where SwiftPM puts `Resources/` — or an empty image when it is not there. Woodcase
    /// draws nothing for an image it cannot load, here and in `AsyncImage`'s placeholder
    /// alike; Pen itself draws a checkerboard placeholder instead (measured 2026-09-27, see
    /// `project/2026-09-27-pen-missing-image-checkerboard.md`), a gap kept on purpose.
    /// `Image(_:bundle:)` looks in asset catalogs, and on macOS it does not find a loose
    /// file. Public, because a component's image prop defaults to one and a caller passes one.
    init(penResource file: String, bundle: Bundle) {
        let url = bundle.url(forResource: file, withExtension: nil)
        #if canImport(UIKit)
            self.init(uiImage: url.flatMap { UIImage(contentsOfFile: $0.path(percentEncoded: false)) } ?? UIImage())
        #else
            self.init(nsImage: url.flatMap { NSImage(contentsOf: $0) } ?? NSImage())
        #endif
    }
}

extension View {
    /// Paints this text with `paint` — Pen's fills, bottom to top — seen through its
    /// glyphs and laid out over the text's whole box, as Pen lays a text's paint out over
    /// the node rather than over each line.
    func penTextFill(@ViewBuilder _ paint: () -> some View) -> some View {
        hidden()
            .overlay { paint() }
            .mask { self }
    }
}
