//
//  PenSupport+Effects.swift
//  Generated by Woodcase. Do not edit.
//
//  Pen's shadows and background blur. Pen casts an outer shadow from a node's silhouette —
//  its shape and the stroke band outside it — opaque whatever its paint, and never lets it
//  show through the node; it draws an inner shadow over the fills and under the children —
//  on text, inside the glyphs. SwiftUI's `.shadow` does neither, so the views use these. A
//  shadow's `radius` is the Gaussian's sigma, half of Pen's `blur`.
//

import SwiftUI

extension View {
    /// Pen's outer shadow, behind this view: cast by `shape` filled opaque, and knocked out
    /// under it, so a translucent fill or stroke shows what is behind the node rather than
    /// its shadow. A stroked shape casts its ``PenSilhouette``, already unioned even-odd where
    /// `shape` is; an unstroked even-odd shape (a ring path with no stroke) is filled
    /// even-odd here so its hole does not cast. On a box under a point on an axis, `outset`
    /// grows the box the silhouette is drawn in, which SwiftUI would not draw, and draws the
    /// shape back inside it (``Shape/penOutset(dx:dy:)``).
    func penDropShadow(
        _ shape: some Shape, color: Color, radius: CGFloat, x: CGFloat = 0, y: CGFloat = 0, blendMode: BlendMode = .normal,
        outset: CGSize = .zero, eoFill: Bool = false
    ) -> some View {
        background {
            let silhouette = shape.penOutset(dx: outset.width, dy: outset.height)
            let style = FillStyle(eoFill: eoFill)
            ZStack {
                silhouette.fill(Color.black, style: style).shadow(color: color, radius: radius, x: x, y: y)
                silhouette.fill(Color.black, style: style).blendMode(.destinationOut)
            }
            .padding(.horizontal, -outset.width)
            .padding(.vertical, -outset.height)
            .compositingGroup()
            .blendMode(blendMode)
        }
    }

    /// Pen's inner shadow, over this view: the shadow `shape`'s outside casts into it.
    /// `eoFill` reads `shape` even-odd, as a ring must be, whose hole is outside it.
    func penInnerShadow(
        _ shape: some Shape, color: Color, radius: CGFloat, x: CGFloat = 0, y: CGFloat = 0,
        blendMode: BlendMode = .normal, eoFill: Bool = false
    ) -> some View {
        overlay {
            PenInnerShadow(shape, color: color, radius: radius, x: x, y: y, blendMode: blendMode, eoFill: eoFill)
        }
    }

    /// Paints this text with `paint` — Pen's fills, bottom to top — and draws `innerShadows`
    /// over it, in order, all seen through its glyphs and laid out over the text's box.
    ///
    /// Pen casts a text's inner shadow from its glyphs drawn opaque, whatever the paint, so
    /// the glyphs that cast it are this view unpainted and styled opaque black: a translucent
    /// fill, or none, still shows the shadow at full strength. The result is one layer, so
    /// a `.shadow` after it is cast once, not by the paint and each inner shadow apart.
    func penTextFill(innerShadows: [PenShadowStyle], @ViewBuilder _ paint: () -> some View) -> some View {
        // Unstyled, the glyphs would draw in `.primary`, which is not opaque: black at 85 %.
        let glyphs = foregroundStyle(Color.black)
        return hidden()
            .overlay { paint() }
            .overlay {
                ZStack {
                    ForEach(innerShadows.indices, id: \.self) { index in
                        PenGlyphInnerShadow(glyphs: glyphs, style: innerShadows[index])
                    }
                }
            }
            .mask { glyphs }
            .compositingGroup()
    }

    /// Pen's background blur, behind this view in `shape`.
    ///
    /// SwiftUI has no backdrop blur of a chosen radius, and a view cannot sample what lies
    /// behind it, so this is a Material: the nearest system look, not Pen's Gaussian of
    /// sigma `radius / 2`. The radius is kept so the intent survives in the source.
    func penBackgroundBlur(_ shape: some Shape, radius _: CGFloat) -> some View {
        background(.ultraThinMaterial, in: shape)
    }
}

/// An inner shadow on its own, for a layer placed between a frame's fills and its children.
///
/// The complement of `shape` — a margin wide enough for the blur and the offset around
/// it, with the shape cut out — casts the shadow, and the result is clipped to the shape,
/// which is how Pen draws it.
struct PenInnerShadow<S: Shape>: View {
    /// The shape the shadow falls inside.
    var shape: S

    /// The shadow's colour.
    var color: Color

    /// The Gaussian's sigma, in points.
    var radius: CGFloat

    /// The horizontal offset, in points.
    var x: CGFloat

    /// The vertical offset, in points.
    var y: CGFloat

    /// How the shadow composites with what is below it.
    var blendMode: BlendMode

    /// Whether `shape` is read even-odd: a ring's hole is outside it, and casts the shadow.
    var eoFill: Bool

    /// A shadow inside `shape`.
    init(
        _ shape: S, color: Color, radius: CGFloat, x: CGFloat = 0, y: CGFloat = 0,
        blendMode: BlendMode = .normal, eoFill: Bool = false
    ) {
        self.shape = shape
        self.color = color
        self.radius = radius
        self.x = x
        self.y = y
        self.blendMode = blendMode
        self.eoFill = eoFill
    }

    var body: some View {
        PenShapeComplement(shape: shape, margin: radius * 3 + abs(x) + abs(y) + 1)
            .fill(Color.black, style: FillStyle(eoFill: true))
            .shadow(color: color, radius: radius, x: x, y: y)
            .clipShape(shape, style: FillStyle(eoFill: eoFill))
            .blendMode(blendMode)
    }
}

/// An inner shadow cast into `glyphs` by everything outside them: a band wide enough for
/// the blur and the offset, with the glyphs cut out, shadowed. It is not clipped to the
/// glyphs itself; `penTextFill(innerShadows:_:)` masks it with them.
struct PenGlyphInnerShadow<Glyphs: View>: View {
    /// The glyphs, styled opaque.
    var glyphs: Glyphs

    /// The shadow.
    var style: PenShadowStyle

    var body: some View {
        let margin = style.radius * 3 + abs(style.x) + abs(style.y) + 1
        ZStack {
            Rectangle().fill(Color.black).padding(-margin)
            glyphs.blendMode(.destinationOut)
        }
        .compositingGroup()
        .shadow(color: style.color, radius: style.radius, x: style.x, y: style.y)
        .blendMode(style.blendMode)
    }
}

/// A band `margin` wide around `shape`'s rectangle with the shape cut out of it; fill it
/// even-odd.
struct PenShapeComplement<S: Shape>: Shape {
    /// The shape cut out.
    var shape: S

    /// How far the band reaches beyond the rectangle, in points.
    var margin: CGFloat

    func path(in rect: CGRect) -> Path {
        var path = Path(rect.insetBy(dx: -margin, dy: -margin))
        path.addPath(shape.path(in: rect))
        return path
    }
}

/// What a stroked shape covers: its outline united with the region its stroke covers, which
/// Pen casts an outer shadow from. United rather than stacked, so no seam shows where the
/// band meets the outline.
struct PenSilhouette<Outline: Shape, Stroke: Shape>: Shape {
    /// The shape's outline.
    var outline: Outline

    /// The region its stroke covers.
    var stroke: Stroke

    /// Whether the outline is filled even-odd.
    var eoFill: Bool

    /// The union of `outline` and `stroke`.
    init(_ outline: Outline, stroke: Stroke, eoFill: Bool = false) {
        self.outline = outline
        self.stroke = stroke
        self.eoFill = eoFill
    }

    func path(in rect: CGRect) -> Path {
        outline.path(in: rect).union(stroke.path(in: rect), eoFill: eoFill)
    }
}
