//
//  PenSupport+CatalogLayout.swift
//  Generated by Woodcase. Do not edit.
//
//  How the generated catalog is laid out. Its rows of specimens wrap at the width of the
//  window it is shown in, so a row never runs off the right edge; a specimen wider than the
//  window — a page, a wide component — keeps its natural size and the window scrolls
//  sideways to reach it. Every specimen is drawn at its ideal size, never squeezed to fit.
//  Rendered without a window (a snapshot), rows wrap at a fixed width instead.
//

import SwiftUI

extension EnvironmentValues {
    /// The width the catalog's rows wrap at: the window's, less the sheet's margins, or a
    /// fixed width when no window sets it.
    @Entry var penCatalogRowWidth: CGFloat = PenCatalogMetrics.snapshotRowWidth
}

/// The catalog's measurements, shared by the sheet and the window that scrolls it.
enum PenCatalogMetrics {
    /// The margin around the sheet, on every side.
    static let margin: CGFloat = 32

    /// The width rows wrap at when no window sets one.
    static let snapshotRowWidth: CGFloat = 1200
}

extension View {
    /// The sheet's page: its margins, filling at least the room it is given, on the
    /// background of the theme's colour scheme.
    func penCatalogPage() -> some View {
        padding(PenCatalogMetrics.margin)
            .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
            .background(.background)
    }

    /// The sheet as a scroll view of a window `size` shows it: rows wrap at the window's
    /// width, and the page is at least as large as the window, so its background fills it
    /// while wider or taller content scrolls.
    func penCatalogViewport(_ size: CGSize) -> some View {
        environment(\.penCatalogRowWidth, max(0, size.width - 2 * PenCatalogMetrics.margin))
            .frame(minWidth: size.width, minHeight: size.height, alignment: .topLeading)
            .background(.background)
    }
}

/// Wraps its content into rows, left to right, at the environment's row width.
struct PenCatalogFlow<Content: View>: View {
    @Environment(\.penCatalogRowWidth) private var rowWidth
    private let content: Content

    /// A flow of `content`'s views.
    init(@ViewBuilder content: () -> Content) {
        self.content = content()
    }

    var body: some View {
        PenCatalogFlowLayout(rowWidth: rowWidth) {
            content
        }
    }
}

/// Places its subviews at their ideal sizes in rows no wider than `rowWidth`, or than the
/// width it is offered when that is narrower. A subview wider than a row has one to itself
/// and makes the flow as wide as it is.
struct PenCatalogFlowLayout: Layout {
    /// The widest a row may be.
    var rowWidth: CGFloat

    /// The space between subviews and between rows.
    var spacing: CGFloat = 24

    func sizeThatFits(proposal: ProposedViewSize, subviews: Subviews, cache _: inout ()) -> CGSize {
        arrange(subviews, proposal: proposal).reduce(CGSize.zero) { size, frame in
            CGSize(width: max(size.width, frame.maxX), height: max(size.height, frame.maxY))
        }
    }

    func placeSubviews(in bounds: CGRect, proposal: ProposedViewSize, subviews: Subviews, cache _: inout ()) {
        // Arranged as they were measured: wrapping at the bounds instead would move rows
        // the flow's height was not measured for.
        for (subview, frame) in zip(subviews, arrange(subviews, proposal: proposal)) {
            subview.place(
                at: CGPoint(x: bounds.minX + frame.minX, y: bounds.minY + frame.minY),
                anchor: .topLeading,
                proposal: ProposedViewSize(frame.size)
            )
        }
    }

    /// Each subview's frame at its ideal size, in rows no wider than the row width or
    /// the proposal's, whichever is narrower.
    private func arrange(_ subviews: Subviews, proposal: ProposedViewSize) -> [CGRect] {
        let width = min(rowWidth, proposal.width ?? .infinity)
        var frames: [CGRect] = []
        var origin = CGPoint.zero
        var rowHeight: CGFloat = 0
        for subview in subviews {
            let size = subview.sizeThatFits(.unspecified)
            if origin.x > 0, origin.x + size.width > width {
                origin = CGPoint(x: 0, y: origin.y + rowHeight + spacing)
                rowHeight = 0
            }
            frames.append(CGRect(origin: origin, size: size))
            origin.x += size.width + spacing
            rowHeight = max(rowHeight, size.height)
        }
        return frames
    }
}
