//
//  PenSupport+Catalog.swift
//  Generated by Woodcase. Do not edit.
//
//  The pieces the generated catalog (`Catalog/PenCatalogSheet.swift`) is built from: a
//  section, an entry per component or page, a captioned specimen per state or text style,
//  a swatch per color token, a value per other token and a column per theme; the flow that
//  wraps them into rows and the window's scrolling are `PenSupport+CatalogLayout.swift`.
//  They draw in the system's own type and colors, so the catalog's chrome never passes for
//  the design it shows.
//

import SwiftUI

/// A titled part of the catalog: the components, the pages, the colors, the type.
struct PenCatalogSection<Content: View>: View {
    private let title: String
    private let content: Content

    /// A section headed `title`, its content stacked below.
    init(_ title: String, @ViewBuilder content: () -> Content) {
        self.title = title
        self.content = content()
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 20) {
            Text(title)
                .font(.title.weight(.semibold))
            content
        }
    }
}

/// One component or page: its name over its specimens, wrapped into rows.
struct PenCatalogEntry<Content: View>: View {
    private let title: String
    private let content: Content

    /// An entry named `title`, its content wrapped into rows.
    init(_ title: String, @ViewBuilder content: () -> Content) {
        self.title = title
        self.content = content()
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 10) {
            Text(title)
                .font(.headline)
            PenCatalogFlow {
                content
            }
        }
    }
}

/// One specimen — a state of a component, a text style — over its caption.
struct PenCatalogSpecimen<Content: View>: View {
    private let caption: String
    private let content: Content

    /// A specimen captioned `caption`.
    init(_ caption: String, @ViewBuilder content: () -> Content) {
        self.caption = caption
        self.content = content()
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            content
            Text(caption)
                .font(.caption.monospaced())
                .foregroundStyle(.secondary)
        }
    }
}

/// A color token: a chip of the color beside the variable's name.
struct PenCatalogSwatch: View {
    private let name: String
    private let color: Color

    /// The swatch of the variable `name`, which reads `color` under the current theme.
    init(_ name: String, color: Color) {
        self.name = name
        self.color = color
    }

    var body: some View {
        HStack(spacing: 8) {
            RoundedRectangle(cornerRadius: 6)
                .fill(color)
                .overlay { RoundedRectangle(cornerRadius: 6).strokeBorder(.secondary.opacity(0.4)) }
                .frame(width: 36, height: 36)
            Text(name)
                .font(.caption.monospaced())
        }
        .frame(width: 220, alignment: .leading)
    }
}

/// A token that is not a color: the variable's name and what it reads.
struct PenCatalogValue: View {
    private let name: String
    private let value: String

    /// The value of the variable `name`, which reads `value` under the current theme.
    init(_ name: String, value: String) {
        self.name = name
        self.value = value
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(name)
                .font(.caption.monospaced())
            Text(value)
                .font(.body.monospaced())
                .foregroundStyle(.secondary)
        }
        .frame(width: 220, alignment: .leading)
    }
}

/// One theme of a side-by-side sheet: the theme's name over the sheet drawn in it.
struct PenCatalogColumn<Content: View>: View {
    private let title: String
    private let content: Content

    /// A column headed `title`.
    init(_ title: String, @ViewBuilder content: () -> Content) {
        self.title = title
        self.content = content()
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            Text(title)
                .font(.title2.monospaced())
                .fixedSize()
                .padding(PenCatalogMetrics.margin)
            content
        }
    }
}
