//
//  PenSupport.swift
//  Generated by Woodcase. Do not edit.
//
//  The few helpers the generated views need beyond SwiftUI itself. This is the only file
//  that branches on the OS release: every view is written for iOS 26 / macOS 26, and the
//  `#available` branches here are what let the same views run on iOS 18 / macOS 15.
//

import CoreText
import SwiftUI

public extension Color {
    /// An sRGB colour from a `0xRRGGBB` literal, the way the .pen file wrote it. Public,
    /// because a component's colour prop defaults to one and a caller passes one.
    init(hex: UInt32, opacity: Double = 1) {
        self.init(
            .sRGB,
            red: Double((hex >> 16) & 0xFF) / 255,
            green: Double((hex >> 8) & 0xFF) / 255,
            blue: Double(hex & 0xFF) / 255,
            opacity: opacity
        )
    }
}

extension View {
    /// Pen's text style: a family at a size and CSS weight (100–900), optionally italic,
    /// with optical sizing pinned off the way Pen draws variable fonts. `lineHeight` is a
    /// multiple of the size, as in the .pen file, and `nil` is Pen's natural pitch for the
    /// font. A `nil` family is the system font.
    func penFont(
        _ family: String? = nil,
        size: CGFloat,
        weight: CGFloat = 400,
        italic: Bool = false,
        lineHeight: CGFloat? = nil
    ) -> some View {
        modifier(PenFontModifier(
            face: PenFontFace(family: family, size: size, weight: weight, italic: italic),
            lineHeight: lineHeight
        ))
    }
}

/// Applies a ``PenFontFace`` and sets its lines at Pen's pitch.
///
/// Pen sets lines the way CSS does: every line box is `lineHeight` tall, and what that
/// adds to (or takes from) the font's ascent and descent is split equally above and
/// below the glyphs. SwiftUI puts all of it on one side, so ``PenLineBox`` moves the text
/// until its first baseline sits where Pen's does. A text with no line height is set at
/// the font's ascent + descent + leading rounded to a whole point, which is Pen's natural
/// pitch and not SwiftUI's — SwiftUI rounds the ascent and descent apart: Inter at 16 pt
/// is 19.36 points, which Pen sets as 19 and SwiftUI as 20, and at 18 pt Pen sets 22 and
/// SwiftUI 21. Both put the first baseline at the rounded ascent.
struct PenFontModifier: ViewModifier {
    /// The face to draw in.
    var face: PenFontFace

    /// The line height as a multiple of the font size, or `nil` for the font's own.
    var lineHeight: CGFloat?

    func body(content: Content) -> some View {
        let font = face.ctFont
        let ascent = CTFontGetAscent(font)
        let descent = CTFontGetDescent(font)
        let natural = ascent + descent + CTFontGetLeading(font)
        // Pen rounds a set line height to a whole point per line, and centres the glyphs in
        // it with the baseline on a whole point; its natural line keeps its first baseline at
        // the rounded ascent, where SwiftUI's own natural line does.
        let points = lineHeight.map { (face.size * $0).rounded() } ?? natural.rounded()
        let firstBaseline = lineHeight == nil
            ? ascent.rounded() : (ascent + (points - ascent - descent) / 2).rounded()
        if #available(iOS 26, macOS 26, *) {
            PenLineBox(firstBaseline: firstBaseline) {
                content.font(Font(font)).lineHeight(.exact(points: points))
            }
        } else if lineHeight != nil {
            // Before iOS 26 SwiftUI has no line height, only extra spacing between
            // lines, which cannot be negative. The box adds the first line's share, so
            // a line box is `points` tall wherever the spacing can reach it: everywhere
            // when lines are looser than the font's own, on the first line otherwise.
            PenLineBox(firstBaseline: firstBaseline, growth: points - natural) {
                content.font(Font(font)).lineSpacing(max(0, points - natural))
            }
        } else {
            // Nor can it set a natural pitch tighter than its own, so it keeps SwiftUI's,
            // and its baseline; the box still rounds the size up as Pen does.
            PenLineBox(firstBaseline: nil) {
                content.font(Font(font))
            }
        }
    }
}

/// A font as a .pen text node names it: family, size, CSS weight and slant.
struct PenFontFace: Hashable {
    /// The family name, or `nil` for the system font.
    var family: String?

    /// The size in points.
    var size: CGFloat

    /// The CSS weight, 100–900.
    var weight: CGFloat

    /// Whether the face is italic.
    var italic: Bool

    private static let weightAxis = 0x7767_6874 // 'wght'

    /// The Core Text font: the weight on the `wght` axis of a variable font, or the cut of
    /// a static one CSS font matching picks (``PenFaceMatching``), and optical sizing
    /// pinned off — Core Text applies it automatically, and Pen does not.
    var ctFont: CTFont {
        // The package's own faces first, so a bundled family resolves to its bundled file.
        PenFonts.register()
        let pinned: [CFString: Any] = [kCTFontOpticalSizeAttribute: "none"]
        var base: CTFont
        if let family {
            var attributes = pinned
            attributes[kCTFontFamilyNameAttribute] = family
            base = CTFontCreateWithFontDescriptor(CTFontDescriptorCreateWithAttributes(attributes as CFDictionary), size, nil)
        } else {
            base = CTFontCreateUIFontForLanguage(.system, size, nil)
                ?? CTFontCreateWithName("Helvetica" as CFString, size, nil)
        }
        if hasWeightAxis(base) {
            var attributes = pinned
            attributes[kCTFontVariationAttribute] = [Self.weightAxis: weight]
            base = CTFontCreateCopyWithAttributes(base, size, nil, CTFontDescriptorCreateWithAttributes(attributes as CFDictionary))
        } else if let family, let face = PenFaceMatching.descriptor(family: family, weight: weight, italic: italic) {
            base = CTFontCreateWithFontDescriptor(CTFontDescriptorCreateCopyWithAttributes(face, pinned as CFDictionary), size, nil)
        }
        // Matching already picked a static family's italic cut when it has one.
        if italic, !CTFontGetSymbolicTraits(base).contains(.traitItalic),
           let slanted = CTFontCreateCopyWithSymbolicTraits(base, size, nil, .traitItalic, .traitItalic)
        {
            return slanted
        }
        return base
    }

    private func hasWeightAxis(_ font: CTFont) -> Bool {
        let axes = CTFontCopyVariationAxes(font) as? [[CFString: Any]] ?? []
        return axes.contains { ($0[kCTFontVariationAxisIdentifierKey] as? Int) == Self.weightAxis }
    }
}
