//
//  PenSupport+Mesh.swift
//  Generated by Woodcase. Do not edit.
//
//  A Pen mesh gradient drawn by SwiftUI's own MeshGradient, written the way the .pen file
//  writes it: a grid of points whose handles are relative and default to a quarter cell.
//

import SwiftUI

/// One vertex of a Pen mesh gradient: its position in the node's unit square, and any
/// Bézier handle that differs from the grid's default, relative to the position.
///
/// A vertex with default handles is an array literal, `[0.5, 0]`.
struct PenMeshVertex: ExpressibleByArrayLiteral {
    /// Where the vertex sits, from `[0, 0]` (top left) to `[1, 1]` (bottom right).
    var position: SIMD2<Float>
    /// The handle toward the previous column, or `nil` for the default.
    var left: SIMD2<Float>?
    /// The handle toward the next column, or `nil` for the default.
    var right: SIMD2<Float>?
    /// The handle toward the previous row, or `nil` for the default.
    var top: SIMD2<Float>?
    /// The handle toward the next row, or `nil` for the default.
    var bottom: SIMD2<Float>?

    /// A vertex at `position`, with the handles that differ from the grid's defaults.
    init(
        _ position: SIMD2<Float>,
        left: SIMD2<Float>? = nil,
        right: SIMD2<Float>? = nil,
        top: SIMD2<Float>? = nil,
        bottom: SIMD2<Float>? = nil
    ) {
        self.position = position
        self.left = left
        self.right = right
        self.top = top
        self.bottom = bottom
    }

    /// A vertex with default handles, written `[x, y]`.
    init(arrayLiteral coordinates: Float...) {
        precondition(coordinates.count == 2, "A mesh vertex is [x, y]")
        self.init(SIMD2(coordinates[0], coordinates[1]))
    }
}

/// A Pen mesh gradient: `columns × rows` vertices, row-major, one color each, drawn as
/// SwiftUI's `MeshGradient` over the box it fills.
///
/// SwiftUI's mesh is not Pen's: Pen shapes each cell as a bicubic patch through its
/// corners' handles and blends the corners' colors, eased by smoothstep, on their
/// unpremultiplied sRGB values; SwiftUI interpolates its own way, premultiplied. So each
/// Pen cell is handed to SwiftUI as `subdivisions × subdivisions` smaller ones, their
/// corners, tangents and colors taken from Pen's patch — within a cell that small the two
/// interpolations agree. Colors resolve in the view's environment, so a color that
/// changes with it (a theme, the color scheme) changes the mesh too.
struct PenMeshGradient: ShapeStyle {
    /// The vertex count across.
    var columns: Int
    /// The vertex count down.
    var rows: Int
    /// The vertices, row-major.
    var points: [PenMeshVertex]
    /// One color per vertex.
    var colors: [Color]

    /// How many SwiftUI cells each Pen cell becomes along each axis.
    static let subdivisions = 8

    /// The `MeshGradient` this mesh draws as, its colors resolved in `environment`.
    func resolve(in environment: EnvironmentValues) -> MeshGradient {
        let patchColumns = columns - 1, patchRows = rows - 1
        let resolved = colors.map { $0.resolve(in: environment) }
        let steps = Self.subdivisions
        let width = patchColumns * steps + 1, height = patchRows * steps + 1
        let patches = (0 ..< patchRows).flatMap { row in
            (0 ..< patchColumns).map { column in patch(column: column, row: row, colors: resolved) }
        }
        var bezierPoints: [MeshGradient.BezierPoint] = []
        var meshColors: [Color] = []
        bezierPoints.reserveCapacity(width * height)
        meshColors.reserveCapacity(width * height)
        for j in 0 ..< height {
            // The patch before and after this row of the refined grid; they differ on a Pen
            // row boundary, where each side keeps its own tangent.
            let (above, v0) = Self.locate(j, steps: steps, count: patchRows, preferLower: true)
            let (below, v1) = Self.locate(j, steps: steps, count: patchRows, preferLower: false)
            for i in 0 ..< width {
                let (before, u0) = Self.locate(i, steps: steps, count: patchColumns, preferLower: true)
                let (after, u1) = Self.locate(i, steps: steps, count: patchColumns, preferLower: false)
                let here = patches[below * patchColumns + after]
                let position = here.position(u1, v1)
                let scale = 1 / Float(3 * steps)
                bezierPoints.append(MeshGradient.BezierPoint(
                    position: position,
                    leadingControlPoint: position - patches[below * patchColumns + before].du(u0, v1) * scale,
                    topControlPoint: position - patches[above * patchColumns + after].dv(u1, v0) * scale,
                    trailingControlPoint: position + here.du(u1, v1) * scale,
                    bottomControlPoint: position + here.dv(u1, v1) * scale
                ))
                meshColors.append(here.color(u1, v1))
            }
        }
        return MeshGradient(
            width: width,
            height: height,
            bezierPoints: bezierPoints,
            colors: meshColors,
            background: .clear,
            smoothsColors: true,
            colorSpace: .device
        )
    }

    /// The patch a refined-grid index falls in, and its parameter there. An index on a
    /// patch boundary belongs to the earlier patch (at 1) when `preferLower`, else to the
    /// later one (at 0).
    private static func locate(_ index: Int, steps: Int, count: Int, preferLower: Bool) -> (Int, Float) {
        var patch = index / steps
        if preferLower, index % steps == 0, patch > 0 { patch -= 1 }
        patch = min(patch, count - 1)
        return (patch, Float(index - patch * steps) / Float(steps))
    }

    /// Pen's patch whose top-left corner is the vertex at `(column, row)`.
    private func patch(column: Int, row: Int, colors: [Color.Resolved]) -> Patch {
        let dx = 0.25 / Float(max(columns - 1, 1)), dy = 0.25 / Float(max(rows - 1, 1))
        func vertex(_ c: Int, _ r: Int) -> (p: SIMD2<Float>, l: SIMD2<Float>, r: SIMD2<Float>, t: SIMD2<Float>, b: SIMD2<Float>) {
            let v = points[r * columns + c]
            return (v.position, v.left ?? [-dx, 0], v.right ?? [dx, 0], v.top ?? [0, -dy], v.bottom ?? [0, dy])
        }
        let tl = vertex(column, row), tr = vertex(column + 1, row)
        let bl = vertex(column, row + 1), br = vertex(column + 1, row + 1)
        // Pen's control net: the corners, their handles, and zero-twist interior points.
        let net: [SIMD2<Float>] = [
            tl.p, tl.p + tl.r, tr.p + tr.l, tr.p,
            tl.p + tl.b, tl.p + tl.r + tl.b, tr.p + tr.l + tr.b, tr.p + tr.b,
            bl.p + bl.t, bl.p + bl.r + bl.t, br.p + br.l + br.t, br.p + br.t,
            bl.p, bl.p + bl.r, br.p + br.l, br.p,
        ]
        let corners = [
            colors[row * columns + column], colors[row * columns + column + 1],
            colors[(row + 1) * columns + column], colors[(row + 1) * columns + column + 1],
        ]
        return Patch(net: net, corners: corners)
    }

    /// One Pen cell: a bicubic Bézier patch and its four corner colors.
    private struct Patch {
        /// The 4 × 4 control net, row-major: rows follow `v`, columns `u`.
        var net: [SIMD2<Float>]
        /// Top left, top right, bottom left, bottom right.
        var corners: [Color.Resolved]

        /// The point on the patch at `(u, v)`, in the unit square.
        func position(_ u: Float, _ v: Float) -> SIMD2<Float> {
            evaluate(Self.bernstein(u), Self.bernstein(v))
        }

        /// ∂position/∂u.
        func du(_ u: Float, _ v: Float) -> SIMD2<Float> {
            evaluate(Self.derivative(u), Self.bernstein(v))
        }

        /// ∂position/∂v.
        func dv(_ u: Float, _ v: Float) -> SIMD2<Float> {
            evaluate(Self.bernstein(u), Self.derivative(v))
        }

        /// Pen's color: the corners blended by smoothstep-eased parameters, on their
        /// unpremultiplied, gamma-encoded sRGB channels.
        func color(_ u: Float, _ v: Float) -> Color {
            let s = u * u * (3 - 2 * u), t = v * v * (3 - 2 * v)
            func blend(_ channel: KeyPath<Color.Resolved, Float>) -> Double {
                let top = corners[0][keyPath: channel] + s * (corners[1][keyPath: channel] - corners[0][keyPath: channel])
                let bottom = corners[2][keyPath: channel] + s * (corners[3][keyPath: channel] - corners[2][keyPath: channel])
                return Double(top + t * (bottom - top))
            }
            return Color(.sRGB, red: blend(\.red), green: blend(\.green), blue: blend(\.blue), opacity: blend(\.opacity))
        }

        /// The net weighted by `wu` along `u` and `wv` along `v`.
        private func evaluate(_ wu: [Float], _ wv: [Float]) -> SIMD2<Float> {
            var sum = SIMD2<Float>(0, 0)
            for row in 0 ..< 4 {
                for column in 0 ..< 4 {
                    sum += wu[column] * wv[row] * net[row * 4 + column]
                }
            }
            return sum
        }

        /// The cubic Bernstein weights at `t`.
        private static func bernstein(_ t: Float) -> [Float] {
            let s = 1 - t
            return [s * s * s, 3 * t * s * s, 3 * t * t * s, t * t * t]
        }

        /// The derivatives of the cubic Bernstein weights at `t`.
        private static func derivative(_ t: Float) -> [Float] {
            let s = 1 - t
            return [-3 * s * s, 3 * s * s - 6 * t * s, 6 * t * s - 3 * t * t, 3 * t * t]
        }
    }
}
