//
//  PenSupport+Image.swift
//  Generated by Woodcase. Do not edit.
//
//  An image paint cropped by Pen's `transform` (format 2.20): SwiftUI's own modifiers place
//  a whole image, but not a window of it sized to the cropped image's aspect.
//

import SwiftUI

/// An image drawn through a Pen crop, filling the box it is offered.
///
/// `crop` maps the image's unit square — (0, 0) its top-left corner, (1, 1) its bottom-right —
/// to the unit square of the crop box. With `.stretch` the crop box is the box; with `.cover`
/// and `.contain` it takes the cropped image's aspect — its sides are the crop square's axes
/// mapped back into the image, measured in the image's own size — scaled to cover or fit the
/// box, centered. Only `.contain` clips to the crop box. The generated views write a cover
/// crop already kept inside the image, so this view never moves it.
struct PenImageCrop: View {
    /// How the crop box is sized into the box.
    enum Placement {
        case stretch, cover, contain
    }

    /// The image.
    var image: Image
    /// How the crop box is sized into the box.
    var placement: Placement
    /// The map from the image's unit square to the crop box's.
    var crop: CGAffineTransform

    init(_ image: Image, placement: Placement, crop: CGAffineTransform) {
        self.image = image
        self.placement = placement
        self.crop = crop
    }

    /// How far past its box the image may be drawn: a stroke outside the box needs it.
    @Environment(\.penPaintBleed) private var bleed

    var body: some View {
        let bleed = bleed
        Canvas { context, size in
            let resolved = context.resolve(image)
            let pixels = resolved.size
            let box = CGSize(width: size.width - 2 * bleed, height: size.height - 2 * bleed)
            let determinant = crop.a * crop.d - crop.b * crop.c
            guard box.width > 0, box.height > 0, pixels.width > 0, pixels.height > 0, determinant != 0 else { return }
            var cropBox = CGRect(x: bleed, y: bleed, width: box.width, height: box.height)
            if placement != .stretch {
                let inverse = crop.inverted()
                let xAxis = (inverse.a * pixels.width, inverse.b * pixels.height)
                let yAxis = (inverse.c * pixels.width, inverse.d * pixels.height)
                let width = (xAxis.0 * xAxis.0 + xAxis.1 * xAxis.1).squareRoot()
                let height = (yAxis.0 * yAxis.0 + yAxis.1 * yAxis.1).squareRoot()
                let scaleX = box.width / width, scaleY = box.height / height
                let scale = placement == .cover ? max(scaleX, scaleY) : min(scaleX, scaleY)
                cropBox = CGRect(
                    x: bleed + (box.width - width * scale) / 2, y: bleed + (box.height - height * scale) / 2,
                    width: width * scale, height: height * scale
                )
            }
            if placement == .contain {
                context.clip(to: Path(cropBox))
            }
            // Pixels → the unit square → the crop's unit square → the crop box.
            let map = CGAffineTransform(scaleX: 1 / pixels.width, y: 1 / pixels.height)
                .concatenating(crop)
                .concatenating(CGAffineTransform(a: cropBox.width, b: 0, c: 0, d: cropBox.height, tx: cropBox.minX, ty: cropBox.minY))
            context.concatenate(map)
            context.draw(resolved, in: CGRect(origin: .zero, size: pixels))
        }
        .padding(-bleed)
    }
}
