//
//  PenSupport+States.swift
//  Generated by Woodcase. Do not edit.
//
//  The states a generated control draws. A control reads which interactions are live from
//  SwiftUI's own sources — `.onHover`, its style's `isPressed`, the `isFocused` and
//  `isEnabled` environment values, or a text field's `@FocusState` — and draws the frame
//  the designer drew for that state, or its smart default. `penControlState(_:)` pins the
//  interactions instead, so a preview or a snapshot can draw any state.
//

import SwiftUI

/// The interactions a generated control is in: any mix of hovered, pressed, focused and
/// disabled.
public struct PenControlState: OptionSet, Hashable, Sendable {
    public let rawValue: Int

    public init(rawValue: Int) {
        self.rawValue = rawValue
    }

    /// The pointer is over the control.
    public static let hovered = PenControlState(rawValue: 1 << 0)

    /// The control is being pressed.
    public static let pressed = PenControlState(rawValue: 1 << 1)

    /// The control has keyboard focus.
    public static let focused = PenControlState(rawValue: 1 << 2)

    /// The control is disabled.
    public static let disabled = PenControlState(rawValue: 1 << 3)
}

public extension View {
    /// Draws the generated controls in this view in `state`, whatever the pointer, the
    /// keyboard and presses do: for previews and snapshots. `.disabled(true)` disables them
    /// as it disables any control.
    func penControlState(_ state: PenControlState) -> some View {
        environment(\.penPinnedControlState, state)
    }
}

extension View {
    /// A focus ring around this view while `isVisible`: a line `width` points wide,
    /// `offset` points outside the view's bounds, in the foreground style, its corners
    /// following the view's `cornerRadius`.
    func penFocusRing(_ isVisible: Bool, width: CGFloat, offset: CGFloat, cornerRadius: CGFloat) -> some View {
        overlay {
            if isVisible {
                let inset = offset + width / 2
                RoundedRectangle(cornerRadius: cornerRadius > 0 ? cornerRadius + inset : 0)
                    .stroke(.foreground, lineWidth: width)
                    .padding(-inset)
            }
        }
    }
}

extension EnvironmentValues {
    /// The interactions `penControlState(_:)` pinned, or `nil` to read the live ones.
    @Entry var penPinnedControlState: PenControlState?
}

/// Reads the state a control is in and draws `content` for it.
///
/// Hover comes from `.onHover`, focus from the `isFocused` environment value — the
/// focusable control around the reader — unless the control passes its own, and
/// disabled from `isEnabled`, which pinning never overrides.
struct PenStateReader<Content: View>: View {
    private let isPressed: Bool
    private let isFocused: Bool?
    private let content: (PenControlState) -> Content

    @Environment(\.isEnabled) private var isEnabled
    @Environment(\.isFocused) private var environmentFocus
    @Environment(\.penPinnedControlState) private var pinned
    @State private var isHovered = false

    /// A reader for a control that is pressed while `isPressed`, and focused while
    /// `isFocused` — or, when that is `nil`, while the focusable control around it is.
    init(
        isPressed: Bool = false,
        isFocused: Bool? = nil,
        @ViewBuilder content: @escaping (PenControlState) -> Content
    ) {
        self.isPressed = isPressed
        self.isFocused = isFocused
        self.content = content
    }

    var body: some View {
        content(state)
            .onHover { isHovered = $0 }
    }

    private var state: PenControlState {
        var state = pinned ?? live
        if !isEnabled {
            state.insert(.disabled)
        }
        return state
    }

    private var live: PenControlState {
        var state: PenControlState = []
        if isHovered {
            state.insert(.hovered)
        }
        if isPressed {
            state.insert(.pressed)
        }
        if isFocused ?? environmentFocus {
            state.insert(.focused)
        }
        return state
    }
}
