//
//  PenSupport+Group.swift
//  Generated by Woodcase. Do not edit.
//
//  Pen's group shadows. A group has no shape of its own, so its shadows are cast by the
//  silhouette of what its children cover, in opaque black, which the page passes in. The
//  outer shadows are knocked out under the silhouette, like a shape's; an inner shadow is
//  cast by everything outside the silhouette and falls inside it, over the children.
//

import SwiftUI

/// One shadow of a group, or one inner shadow of a text. `radius` is the Gaussian's sigma, half of Pen's `blur`.
struct PenShadowStyle {
    /// The shadow's colour.
    var color: Color

    /// The Gaussian's sigma, in points.
    var radius: CGFloat

    /// The horizontal offset, in points.
    var x: CGFloat

    /// The vertical offset, in points.
    var y: CGFloat

    /// How the shadow composites with what is below it.
    var blendMode: BlendMode

    /// A shadow of `color`, blurred by `radius`, moved by `x` and `y`.
    init(color: Color, radius: CGFloat, x: CGFloat = 0, y: CGFloat = 0, blendMode: BlendMode = .normal) {
        self.color = color
        self.radius = radius
        self.x = x
        self.y = y
        self.blendMode = blendMode
    }
}

extension View {
    /// A group's shadows: `outer` behind this view, the first lowest, and `inner` over it,
    /// all cast by `silhouette`, which is laid out from this view's top-leading corner.
    func penGroupShadows(
        outer: [PenShadowStyle] = [], inner: [PenShadowStyle] = [], @ViewBuilder silhouette: () -> some View
    ) -> some View {
        let shape = silhouette().compositingGroup()
        return background(alignment: .topLeading) {
            ZStack(alignment: .topLeading) {
                ForEach(outer.indices, id: \.self) { index in
                    let style = outer[index]
                    ZStack(alignment: .topLeading) {
                        shape.shadow(color: style.color, radius: style.radius, x: style.x, y: style.y)
                        shape.blendMode(.destinationOut)
                    }
                    .compositingGroup()
                    .blendMode(style.blendMode)
                }
            }
        }
        .overlay(alignment: .topLeading) {
            ZStack(alignment: .topLeading) {
                ForEach(inner.indices, id: \.self) { index in
                    let style = inner[index]
                    // A band wide enough for the blur and the offset, with the silhouette cut out.
                    let margin = style.radius * 3 + abs(style.x) + abs(style.y) + 1
                    ZStack(alignment: .topLeading) {
                        Rectangle().fill(Color.black).padding(-margin)
                        shape.blendMode(.destinationOut)
                    }
                    .compositingGroup()
                    .shadow(color: style.color, radius: style.radius, x: style.x, y: style.y)
                    .mask(alignment: .topLeading) { shape }
                    .blendMode(style.blendMode)
                }
            }
        }
    }
}
