//
//  PenSupport+LineHeight.swift
//  Generated by Woodcase. Do not edit.
//
//  Where a text's lines sit at Pen's line height: Pen centres the glyphs in each
//  line box (CSS's half-leading), SwiftUI does not.
//

import SwiftUI

/// Holds one text and places it so its first baseline lands `firstBaseline` below the
/// box's top, measured from the baseline SwiftUI reports rather than assumed, and makes
/// the box `growth` taller than the text.
///
/// The box is the text's size rounded up to whole points, as Pen measures a text node
/// (the rule of Woodcase's `PenTextMeasurer`): SwiftUI's own size is fractional, so a
/// `fit_content` frame around it would land a fraction of a point narrower than Pen's.
struct PenLineBox: Layout {
    /// Where the first line's baseline sits, from the top of the box, or `nil` to leave it
    /// where SwiftUI sets it.
    var firstBaseline: CGFloat?

    /// How much taller than its text the box is: the leading SwiftUI did not lay out.
    var growth: CGFloat = 0

    func sizeThatFits(proposal: ProposedViewSize, subviews: Subviews, cache _: inout ()) -> CGSize {
        guard let text = subviews.first else { return .zero }
        let size = text.sizeThatFits(inner(proposal))
        return CGSize(width: size.width.rounded(.up), height: max(0, size.height + growth).rounded(.up))
    }

    func placeSubviews(in bounds: CGRect, proposal _: ProposedViewSize, subviews: Subviews, cache _: inout ()) {
        guard let text = subviews.first else { return }
        let proposal = inner(ProposedViewSize(width: bounds.width, height: bounds.height))
        let shift = firstBaseline.map { $0 - text.dimensions(in: proposal)[VerticalAlignment.firstTextBaseline] } ?? 0
        text.place(
            at: CGPoint(x: bounds.minX, y: bounds.minY + shift),
            anchor: .topLeading,
            proposal: proposal
        )
    }

    /// The proposal the text sees: the box's, less the growth.
    private func inner(_ proposal: ProposedViewSize) -> ProposedViewSize {
        ProposedViewSize(width: proposal.width, height: proposal.height.map { max(0, $0 - growth) })
    }
}
