import Foundation
import Testing
@testable import Woodcase

/// What `kit.lib.pen` and `banking.pen` promise the import pipeline, stated outright.
///
/// The library is generated by `scripts/gen-kit-fixture`; its ids are fixed by that
/// script's keys, and the ids named here are the ones it prints for
/// `--ids row-divided field-text/box action-solid-lg/caption …`. The screen tests in
/// ``PenBankingAppTests`` only show that the pair renders close to Pen; these show
/// *which* import cases it renders through, so a regenerated library that quietly
/// dropped one fails here rather than passing a loose MAE.
struct KitLibraryFixtureTests {
    /// `Tests/WoodcaseTests/Fixtures`.
    private let fixturesDir = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()
        .appendingPathComponent("Fixtures")

    /// Ids from `scripts/gen-kit-fixture --ids <key>`.
    private enum Kit {
        /// `row-divided`: a bottom-only hairline.
        static let rowDivided = "tGiic"
        /// `field-text/box`: stroked with `$stroke-weight`.
        static let fieldBox = "mFxEX"
        /// `action-solid-lg/caption`: the label every large glyph-action disables.
        static let largeCaption = "Wb3kd"
        /// `action-solid-lg/mark`: the icon the host overrides through `M7RGT/V:…`.
        static let largeMark = "Xxvji"
        /// `action-soft-md/glyph`: the icon box inside the bell button.
        static let softGlyph = "KssvD"
    }

    /// The generated library, parsed.
    private func library() throws -> PenDocument {
        try PenParser.parse(contentsOf: fixturesDir.appendingPathComponent("kit.lib.pen"))
    }

    /// The host, imported, expanded and resolved at the given root theme.
    private func banking(theme: [String: String]) throws -> PenDocument {
        let host = try PenParser.parse(contentsOf: fixturesDir.appendingPathComponent("banking.pen"))
        let imported = try PenImportResolver.resolve(host, libraries: ["kit.lib.pen": library()])
        return PenVariableResolver.resolve(PenRefExpander.expand(imported), theme: theme)
    }

    // MARK: - The library itself

    @Test("The library is library-scale: 80+ reusable components")
    func libraryScale() throws {
        let reusable = try Self.flatten(library().children).filter { $0.node.common.reusable == true }
        #expect(reusable.count >= 80, "only \(reusable.count) reusable components")
    }

    @Test("The library has three theme axes, one with more than two options")
    func threeAxes() throws {
        let themes = try #require(try library().themes)
        #expect(Set(themes.keys) == ["scheme", "tint", "contrast"])
        #expect(themes["tint"]?.count == 4)
    }

    @Test("The third axis moves a number and a color token")
    func contrastAxisResolves() throws {
        let normal = try Self.index(PenVariableResolver.resolve(
            library(), theme: ["scheme": "night", "tint": "moss", "contrast": "normal"]
        ))
        let high = try Self.index(PenVariableResolver.resolve(
            library(), theme: ["scheme": "night", "tint": "moss", "contrast": "high"]
        ))

        guard case let .frame(normalBox) = try #require(normal[Kit.fieldBox]).node.kind,
              case let .frame(highBox) = try #require(high[Kit.fieldBox]).node.kind,
              case let .frame(highRow) = try #require(high[Kit.rowDivided]).node.kind
        else {
            Issue.record("expected frames")
            return
        }
        #expect(normalBox.strokeWidth == .uniform(.literal(1)))
        #expect(highBox.strokeWidth == .uniform(.literal(2)))
        #expect(Self.color(highRow.stroke) == "#ffffff52")
    }

    @Test("A per-side stroke survives resolution as one side")
    func perSideStroke() throws {
        guard case let .frame(row) = try #require(try Self.index(library())[Kit.rowDivided]).node.kind else {
            Issue.record("expected a frame")
            return
        }
        #expect(row.strokeWidth == .perSide(PenStrokeWidth.Sides(top: nil, right: nil, bottom: .literal(1), left: nil)))
    }

    // MARK: - Across the import

    @Test("A two-deep library ref chain expands, and slash-path overrides reach through it")
    func chainAndSlashPathOverrides() throws {
        let nodes = try Self.flatten(banking(theme: ["scheme": "day", "V:scheme": "day"]).children)
        let icons = nodes.compactMap { entry -> String? in
            guard entry.node.id.hasPrefix("8ruxp/"), entry.node.id.hasSuffix("V:\(Kit.largeMark)"),
                  case let .icon(data) = entry.node.kind, case let .literal(name) = data.icon
            else { return nil }
            return name
        }
        #expect(Set(icons) == ["arrow-up-right", "arrow-down-left", "credit-card", "plus"])
    }

    @Test("A glyph-action's disabled caption stays out of its layout")
    func disabledCaptionOutOfLayout() throws {
        let document = try banking(theme: ["scheme": "day", "V:scheme": "day"])
        let rects = PenLayoutEngine.layout(document)
        let captions = Self.flatten(document.children).filter {
            $0.node.id.hasPrefix("8ruxp/") && $0.node.id.hasSuffix("V:\(Kit.largeCaption)")
        }
        try #require(captions.count == 4)
        for caption in captions {
            #expect(caption.node.common.enabled == .literal(false), "\(caption.node.id)")
            let button = try #require(caption.parent)
            // 22 pt glyph box plus 10 pt padding each side; a measured caption would widen it.
            #expect(rects[button.id]?.width == 42, "\(button.id) is \(String(describing: rects[button.id]))")
        }
    }

    @Test("A placed screen's theme reaches library nodes on two axes at once")
    func twoAxisThemeAcrossTheImport() throws {
        let nodes = try Self.flatten(banking(theme: ["scheme": "day", "V:scheme": "day"]).children)
        func bellFill(screen: String) -> String? {
            nodes.first {
                $0.node.id.hasPrefix("\(screen)/") && $0.node.id.hasSuffix("V:\(Kit.softGlyph)")
            }.flatMap { entry -> String? in
                guard case let .frame(data) = entry.parent?.kind else { return nil }
                return Self.color(data.fills)
            }
        }
        // `$accent-wash` for day+moss and night+moss: neither is the library's default tint.
        #expect(bellFill(screen: "8ruxp") == "#e1eedf")
        #expect(bellFill(screen: "YGJ0d") == "#1f3325")
    }

    // MARK: - Helpers

    /// A node with the parent it was found under.
    private struct Entry {
        /// The node.
        let node: PenNode
        /// Its parent, or `nil` at the top level.
        let parent: PenNode?
    }

    /// Every node under `nodes`, depth first, with its parent.
    private static func flatten(_ nodes: [PenNode], parent: PenNode? = nil) -> [Entry] {
        nodes.flatMap { node -> [Entry] in
            let children: [PenNode] = switch node.kind {
            case let .frame(data): data.children ?? []
            case let .group(data): data.children ?? []
            default: []
            }
            return [Entry(node: node, parent: parent)] + flatten(children, parent: node)
        }
    }

    /// Every node of `document` by id; the first wins on a repeat.
    private static func index(_ document: PenDocument) -> [String: Entry] {
        Dictionary(flatten(document.children).map { ($0.node.id, $0) }, uniquingKeysWith: { first, _ in first })
    }

    /// A solid fill's color, lowercased, however the JSON spelled it.
    private static func color(_ fills: PenFills?) -> String? {
        switch fills?.all.first {
        case let .shorthand(value): value.lowercased()
        case let .color(fill): if case let .literal(value) = fill.color { value.lowercased() } else { nil }
        default: nil
        }
    }
}
