import CoreGraphics
import Foundation
import ImageIO
import Testing
import UniformTypeIdentifiers
@testable import Woodcase

/// Smoke tests that render the banking app fixture through the full pipeline,
/// including import resolution of the `kit.lib.pen` component library.
///
/// This fixture is a mobile banking app built on `kit.lib.pen` (80+ imported
/// components, generated by `scripts/gen-kit-fixture`), with day and night screens. These tests verify the
/// full pipeline — parse → import resolution → ref expansion → variable resolution
/// → layout → render — and compare output against Pencil reference exports via MAE.
struct PenBankingAppTests {
    /// The kit sets Inter throughout; without it the screens measure the fallback face.
    init() {
        TestFontRegistration.registerTestFonts()
    }

    private let fixturesDir = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()
        .appendingPathComponent("Fixtures")

    private let outputDir = TestOutputDirectory.url

    /// Measured 0.756 (day) and 0.891 (night) on 2026-09-27, once lines were placed as Pen
    /// places them and Inter kept its default optical size (leaf HVBKsf), with
    /// `swift test -j 3 --filter PenBankingAppTests`; the margin rule over the night screen
    /// sets 1.34. Before that they measured 3.106 and 3.209 on 2026-09-26 with Inter registered and text
    /// set at Pen's rounded natural line height, with `swift test --filter PenBankingAppTests`;
    /// the margin rule (max(measured×1.5, measured+0.25) over the worse of the two, night)
    /// set 4.82. Before, the screens drew in a fallback face and scored 3.35 and 3.25 under a
    /// bar of 5.03; with Inter but Core Text's own line height (19.36 pt rounded up to 20 at
    /// 16 pt, where Pen sets 19) every line ran a point tall and they scored 5.99 and 5.43.
    /// The exports are from headless `pen interactive` (pen CLI 0.3.5); the shadcn pair this
    /// fixture replaced allowed 40.
    /// A whole-image mean is still blunt: a row of four wrongly expanded buttons scored
    /// only 4.68, which is why ``KitLibraryFixtureTests`` asserts the import cases directly.
    private static let maeThreshold = 1.34

    // MARK: - Pipeline

    /// Loads the banking fixture with the kit library, resolves imports, expands refs,
    /// and resolves variables for the given theme.
    private func loadAndProcess(theme: [String: String] = [:]) throws -> PenDocument {
        let bankingURL = fixturesDir.appendingPathComponent("banking.pen")
        let kitURL = fixturesDir.appendingPathComponent("kit.lib.pen")

        let banking = try PenParser.parse(contentsOf: bankingURL)
        let kit = try PenParser.parse(contentsOf: kitURL)

        // Stage 1: Resolve imports
        let imported = PenImportResolver.resolve(
            banking,
            libraries: ["kit.lib.pen": kit]
        )

        // Stage 2: Expand refs
        let expanded = PenRefExpander.expand(imported)

        // Stage 3: Resolve variables with theme
        return PenVariableResolver.resolve(expanded, theme: theme)
    }

    /// Renders a screen, saves the output PNG, and compares against the Pencil reference.
    private func renderAndCompare(
        theme: [String: String] = [:],
        screenName: String,
        screenID: String,
        outputName: String
    ) throws -> (image: CGImage, mae: Double) {
        let document = try loadAndProcess(theme: theme)
        let rects = PenLayoutEngine.layout(document)
        guard let screenRect = rects[screenID] else {
            throw BankingTestError.noScreen(screenName)
        }
        let size = CGSize(width: screenRect.width, height: screenRect.height)

        guard let image = PenRenderer.render(
            document,
            layoutRects: rects,
            size: size,
            scale: 2,
            rootNodeID: screenID
        ) else {
            throw BankingTestError.renderFailed(outputName)
        }

        // Save PNG for visual inspection
        try FileManager.default.createDirectory(at: outputDir, withIntermediateDirectories: true)
        let outputURL = outputDir.appendingPathComponent("banking-\(outputName).png")
        guard let dest = CGImageDestinationCreateWithURL(
            outputURL as CFURL,
            UTType.png.identifier as CFString,
            1,
            nil
        ) else {
            throw BankingTestError.saveFailed(outputName)
        }
        CGImageDestinationAddImage(dest, image, nil)
        guard CGImageDestinationFinalize(dest) else {
            throw BankingTestError.saveFailed(outputName)
        }
        print("Saved: \(outputURL.path)")

        // Compare against Pencil reference
        let reference = PenSnapshotTestHelpers.loadFixtureImage(
            named: "banking-home-\(outputName)", fixturesDir: fixturesDir
        )
        let mae: Double
        if let reference {
            mae = PenSnapshotTestHelpers.meanAbsoluteError(between: image, and: reference)
            print("  banking-\(outputName) MAE vs Pencil: \(String(format: "%.3f", mae))")
        } else {
            mae = .infinity
            print("  banking-\(outputName): no reference image found")
        }

        return (image, mae)
    }

    enum BankingTestError: Error {
        case noScreen(String)
        case renderFailed(String)
        case saveFailed(String)
    }

    // MARK: - Diagnostics

    /// Recursively counts ref nodes remaining in the tree (unresolved refs).
    private func countRefs(in nodes: [PenNode]) -> [(id: String, ref: String)] {
        var refs: [(id: String, ref: String)] = []
        for node in nodes {
            if case let .ref(data) = node.kind {
                refs.append((id: node.id, ref: data.ref))
            }
            switch node.kind {
            case let .frame(data):
                if let children = data.children { refs.append(contentsOf: countRefs(in: children)) }
            case let .group(data):
                if let children = data.children { refs.append(contentsOf: countRefs(in: children)) }
            default: break
            }
        }
        return refs
    }

    @Test("No unresolved refs remain after expansion")
    func noUnresolvedRefs() throws {
        let document = try loadAndProcess(theme: ["scheme": "day", "V:scheme": "day"])
        let unresolvedRefs = countRefs(in: document.children)
        for ref in unresolvedRefs {
            print("  Unresolved ref: \(ref.id) → \(ref.ref)")
        }
        #expect(unresolvedRefs.isEmpty, "Found \(unresolvedRefs.count) unresolved refs")
    }

    // MARK: - Light Mode

    @Test("Banking Home (Light) renders and matches Pencil reference")
    func bankingHomeLight() throws {
        let result = try renderAndCompare(
            theme: ["scheme": "day", "V:scheme": "day"],
            screenName: "banking-home / Light",
            screenID: "8ruxp/nSNTs",
            outputName: "light"
        )
        #expect(result.image.width > 0)
        #expect(result.mae < Self.maeThreshold, "MAE \(result.mae) exceeds threshold")
    }

    // MARK: - Dark Mode

    @Test("Banking Home (Dark) renders and matches Pencil reference")
    func bankingHomeDark() throws {
        let result = try renderAndCompare(
            theme: ["scheme": "night", "V:scheme": "night"],
            screenName: "banking-home / Dark",
            screenID: "YGJ0d/nSNTs",
            outputName: "dark"
        )
        #expect(result.image.width > 0)
        #expect(result.mae < Self.maeThreshold, "MAE \(result.mae) exceeds threshold")
    }
}
