//
//  SwiftUIEmitterPackageTests.swift
//  WoodcaseTests
//

import Foundation
import Testing
@testable import Woodcase

/// What makes the emitted package something a person can take and use: a manifest that
/// always declares its resources, a resource directory that always exists, the text
/// families the views set (which `woodcase generate swiftui` bundles), and the support
/// file that registers every bundled font from its file. That the package really builds
/// and registers them is `SwiftUIPackageBuildTests`, in the command tests.
@Suite("SwiftUIEmitter packaging")
struct SwiftUIEmitterPackageTests {
    // MARK: - The manifest

    @Test("Package.swift processes Resources even when the document bundles nothing")
    func manifestAlwaysDeclaresResources() throws {
        let manifest = try file("Package.swift", in: "layout-nested", module: "Acme")
        #expect(manifest.contains(##".target(name: "Acme", resources: [.process("Resources")])"##))
    }

    @Test("Package.swift is regenerated on every run, and says so under its tools version")
    func manifestIsRegenerated() throws {
        let manifest = try #require(SwiftUIFixtures.emit("layout-nested").files.first { $0.path == "Package.swift" })
        #expect(manifest.writePolicy == .always)
        #expect(manifest.content.hasPrefix("// swift-tools-version: 6.2\n"))
        #expect(manifest.content.contains("Generated by Woodcase"))
    }

    @Test("The Resources directory is always written, so the path Package.swift declares exists")
    func resourcesDirectoryAlwaysExists() throws {
        let paths = try SwiftUIFixtures.emit("layout-nested", options: .init(moduleName: "Acme")).files.map(\.path)
        #expect(paths.contains("Sources/Acme/Resources/.gitkeep"))
    }

    // MARK: - Text families

    @Test("The text families the views set are reported, one entry per family")
    func literalFamilies() throws {
        let result = try emit(children: [
            text(id: "a", family: "Pack Serif"),
            text(id: "b", family: "Pack Serif"),
            text(id: "c", family: "Pack Sans"),
        ])
        #expect(result.fontFamilies == ["Pack Sans", "Pack Serif"])
    }

    @Test("The faces the views set are reported: each family at each weight and style it is drawn in")
    func literalFaces() throws {
        let result = try emit(children: [
            text(id: "a", family: "Pack Serif"),
            text(id: "b", family: "Pack Serif", extra: #", "fontWeight": "700", "fontStyle": "italic""#),
            text(id: "c", family: "Pack Sans", extra: #", "fontWeight": "semibold""#),
        ])
        #expect(result.fontFaces == [
            PenFontFace(family: "Pack Serif", weight: 400, style: .normal),
            PenFontFace(family: "Pack Serif", weight: 700, style: .italic),
            PenFontFace(family: "Pack Sans", weight: 600, style: .normal),
        ])
    }

    @Test("A disabled text's family is not reported: nothing draws it")
    func disabledFamilyLeftOut() throws {
        let result = try emit(children: [
            text(id: "a", family: "Pack Serif", extra: #", "enabled": false"#),
            text(id: "b", family: "Pack Sans"),
        ])
        #expect(result.fontFamilies == ["Pack Sans"])
    }

    @Test("A text, an icon or an image inside a group is bundled like any other")
    func groupedResourcesBundled() throws {
        let group = ##"{"type": "group", "id": "g", "children": [\##(text(id: "t", family: "Pack Serif")), {"type": "icon", "id": "i", "width": 24, "height": 24, "library": "lucide", "icon": "star"}, {"type": "rectangle", "id": "r", "width": 10, "height": 10, "fill": {"type": "image", "url": "./images/a.png"}}]}"##
        let result = try emit(children: [group])
        #expect(result.fontFamilies == ["Pack Serif"])
        #expect(result.iconLibraries == ["lucide"])
        #expect(result.imageAssetURLs == ["./images/a.png"])
    }

    @Test("A family set through a variable reports every value the variable takes")
    func variableFamilies() throws {
        let result = try SwiftUIFixtures.emit("woodcase-app")
        #expect(result.fontFamilies == ["IBM Plex Sans"])
    }

    // MARK: - Registration

    @Test("PenFonts registers every bundled font from its file URL, never from data")
    func penFontsRegistersFromURLs() throws {
        let fonts = try #require(SwiftUIEmitter.supportTemplates()["PenSupport+Fonts.swift"])
        #expect(fonts.contains("public enum PenFonts"))
        #expect(fonts.contains("public static func register()"))
        #expect(fonts.contains("CTFontManagerRegisterFontsForURL"))
        #expect(fonts.contains("Bundle.module"))
        #expect(!fonts.contains("FromData"))
    }

    @Test("A text face and an icon glyph both register the package's fonts before they draw")
    func facesRegisterFirst() throws {
        let support = try #require(SwiftUIEmitter.supportTemplates()["PenSupport.swift"])
        #expect(support.contains("PenFonts.register()"))
        let shape = try #require(SwiftUIEmitter.supportTemplates()["PenSupport+Shape.swift"])
        #expect(shape.contains("PenFonts.font(file:"))
        #expect(!shape.contains("enum PenIconFonts"))
    }

    @Test("The catalog executable lists the bundled fonts and whether each registered")
    func catalogListsFonts() throws {
        let main = try file("Sources/AcmeCatalog/main.swift", in: "layout-nested", module: "Acme")
        #expect(main.contains(#""--fonts""#))
        #expect(main.contains("PenFonts.faces"))
    }

    // MARK: - Helpers

    private func file(_ path: String, in fixture: String, module: String) throws -> String {
        let files = try SwiftUIFixtures.emit(fixture, options: .init(moduleName: module)).files
        return try #require(files.first { $0.path == path }, "\(fixture) emitted no \(path)").content
    }

    private func text(id: String, family: String, extra: String = "") -> String {
        ##"{"type": "text", "id": "\##(id)", "content": "Hi", "fontFamily": "\##(family)"\##(extra)}"##
    }

    private func emit(children: [String]) throws -> EmitResult {
        let json = ##"{"version": "2.17", "children": [{"type": "frame", "id": "root", "name": "Board", "children": [\##(children.joined(separator: ", "))]}]}"##
        let document = try PenParser.parse(Data(json.utf8))
        return try SwiftUIEmitter.emit(
            document: document, components: [], pages: PageAnalyzer.analyze(document),
            theme: ThemeAnalyzer.analyze(document)
        )
    }
}
