//
//  SwiftUIEmitterThemeTests.swift
//  WoodcaseTests
//

import Foundation
import Testing
@testable import Woodcase

/// The theme the SwiftUI emitter writes beside the views: `Theme/PenTheme.swift`, a typed
/// value with one enum per axis and one property per variable, and
/// `Theme/PenTheme+Environment.swift`, which carries it in the environment, sets it on a
/// subtree and bridges a light/dark axis to SwiftUI's color scheme.
/// ``SwiftUIEmitterThemeReadTests`` covers the views that read it.
struct SwiftUIEmitterThemeTests {
    private static let themePath = "Sources/PenUI/Theme/PenTheme.swift"
    private static let environmentPath = "Sources/PenUI/Theme/PenTheme+Environment.swift"

    // MARK: - Files

    @Test("A document with variables emits the theme and its environment under Theme/")
    func themeFiles() throws {
        let files = try Self.files(SwiftUIFixtures.emit("parser-themed-variables"))
        let theme = try #require(files[Self.themePath])
        #expect(theme.hasPrefix("//\n//  PenTheme.swift\n//  Generated by Woodcase from the document's themes and variables. Do not edit.\n//\n\nimport SwiftUI\n"))
        #expect(theme.contains("public struct PenTheme: Hashable, Sendable {"))
        #expect(files[Self.environmentPath] != nil)
    }

    @Test("A document with neither themes nor variables emits no theme")
    func noTheme() throws {
        let files = try Self.files(SwiftUIFixtures.emit("layout-gap"))
        #expect(!files.keys.contains { $0.contains("/Theme/") })
    }

    // MARK: - Axes

    @Test("Each axis is an enum of its options, and the theme defaults to each axis's first")
    func axes() throws {
        let theme = try Self.theme(SwiftUIFixtures.emit("parser-themed-variables"))
        #expect(theme.contains("    public enum Density: String, CaseIterable, Hashable, Sendable {\n        case compact\n        case regular\n    }"))
        #expect(theme.contains("    public enum Mode: String, CaseIterable, Hashable, Sendable {\n        case light\n        case dark\n    }"))
        #expect(theme.contains("    public var density: Density\n"))
        #expect(theme.contains("    public init(density: Density = .compact, mode: Mode = .light) {"))
    }

    @Test("An option that is no Swift identifier keeps its spelling as the raw value")
    func optionNames() throws {
        let theme = try Self.theme(Self.emit(
            themes: ##"{"density": ["default", "extra-compact"]}"##,
            variables: ##"{"gap": {"type": "number", "value": [{"theme": {"density": "default"}, "value": 8}, {"theme": {"density": "extra-compact"}, "value": 2}]}}"##
        ))
        #expect(theme.contains("        case `default`\n"))
        #expect(theme.contains("        case extraCompact = \"extra-compact\"\n"))
        #expect(theme.contains("public init(density: Density = .default)"))
        #expect(theme.contains("        case .extraCompact: 2\n"))
    }

    // MARK: - Variables

    @Test("A variable themed on one axis switches on that axis alone")
    func oneAxis() throws {
        let theme = try Self.theme(SwiftUIFixtures.emit("parser-themed-variables"))
        #expect(theme.contains("""
            /// `$bgColor`.
            var bgColor: Color {
                switch mode {
                case .light: Color(hex: 0xFFFFFF)
                case .dark: Color(hex: 0x1A1A1A)
                }
            }
        """))
        #expect(theme.contains("""
            var textSize: CGFloat {
                switch density {
                case .compact: 14
                case .regular: 18
                }
            }
        """))
    }

    @Test("A variable themed on two axes switches on both")
    func twoAxes() throws {
        let theme = try Self.theme(Self.emit(
            themes: ##"{"mode": ["light", "dark"], "contrast": ["normal", "high"]}"##,
            variables: ##"""
            {"ink": {"type": "color", "value": [
                {"theme": {"mode": "light"}, "value": "#333333"}, {"theme": {"mode": "dark"}, "value": "#CCCCCC"},
                {"theme": {"mode": "light", "contrast": "high"}, "value": "#000000"},
                {"theme": {"mode": "dark", "contrast": "high"}, "value": "#FFFFFF"}]}}
            """##
        ))
        #expect(theme.contains("""
                switch (contrast, mode) {
                case (.normal, .light): Color(hex: 0x333333)
                case (.normal, .dark): Color(hex: 0xCCCCCC)
                case (.high, .light): Color(hex: 0x000000)
                case (.high, .dark): Color(hex: 0xFFFFFF)
                }
        """))
    }

    @Test("A plain variable is a constant, and a translucent color keeps its opacity")
    func plainVariable() throws {
        let theme = try Self.theme(Self.emit(
            themes: ##"{"mode": ["light", "dark"]}"##,
            variables: ##"{"white": {"type": "color", "value": "#FFFFFF"}, "veil": {"type": "color", "value": "#00000080"}, "title": {"type": "string", "value": "Hi"}, "on": {"type": "boolean", "value": true}}"##
        ))
        #expect(theme.contains("    var white: Color {\n        Color(hex: 0xFFFFFF)\n    }"))
        #expect(theme.contains("    var veil: Color {\n        Color(hex: 0x000000, opacity: 0.502)\n    }"))
        #expect(theme.contains("    var title: String {\n        \"Hi\"\n    }"))
        #expect(theme.contains("    var on: Bool {\n        true\n    }"))
    }

    @Test("An unconditional default serves the options no specific value names, and a chain reads its end")
    func defaultsAndChains() throws {
        let theme = try Self.theme(Self.emit(
            themes: ##"{"mode": ["light", "dark"]}"##,
            variables: ##"""
            {"base": {"type": "color", "value": [{"theme": {"mode": "dark"}, "value": "#000000"}, {"value": "#FFFFFF"}]},
             "surface": {"type": "color", "value": "$base"}}
            """##
        ))
        let expected = "switch mode {\n        case .light: Color(hex: 0xFFFFFF)\n        case .dark: Color(hex: 0x000000)\n        }"
        #expect(theme.contains("var base: Color {\n        \(expected)"))
        #expect(theme.contains("var surface: Color {\n        \(expected)"))
    }

    @Test("A variable's name becomes a Swift identifier that no axis property shadows")
    func variableNames() throws {
        let theme = try Self.theme(Self.emit(
            themes: ##"{"mode": ["light", "dark"]}"##,
            variables: ##"{"bg-page": {"type": "color", "value": "#FFFFFF"}, "mode": {"type": "number", "value": 2}}"##
        ))
        #expect(theme.contains("var bgPage: Color {"))
        #expect(theme.contains("var mode2: CGFloat {"))
    }

    // MARK: - Environment

    @Test("A light/dark axis follows SwiftUI's color scheme, and setting it sets the scheme")
    func colorSchemeBridge() throws {
        let environment = try Self.environment(SwiftUIFixtures.emit("parser-themed-variables"))
        #expect(environment.contains("    var penTheme: PenTheme {"))
        #expect(environment.contains("theme.mode = PenTheme.Mode(colorScheme)"))
        #expect(environment.contains("colorScheme = newValue.mode.colorScheme"))
        #expect(environment.contains("@Entry var penThemeAxes = PenTheme()"))
        #expect(environment.contains("public extension PenTheme.Mode {"))
    }

    @Test("A document whose axes are not light and dark carries its theme without the bridge")
    func noBridge() throws {
        let environment = try Self.environment(SwiftUIFixtures.emit("banking"))
        #expect(environment.contains("    var penTheme: PenTheme {\n        get { penThemeAxes }\n        set { penThemeAxes = newValue }\n    }"))
        #expect(!environment.contains("colorScheme"))
    }

    @Test("A subtree sets the theme on the axes it names, and a reader hands it to its content")
    func modifierAndReader() throws {
        let environment = try Self.environment(SwiftUIFixtures.emit("parser-themed-variables"))
        #expect(environment.contains("    func penTheme(density: PenTheme.Density? = nil, mode: PenTheme.Mode? = nil) -> some View {"))
        #expect(environment.contains("transformEnvironment(\\.penTheme) { theme in"))
        #expect(environment.contains("public struct PenThemeReader<Content: View>: View {"))
    }

    // MARK: - Helpers

    /// Emit a document of one empty page with `themes` and `variables` (JSON objects).
    static func emit(themes: String, variables: String, children: String = ##"{"type": "frame", "id": "root", "name": "Board", "width": 10, "height": 10}"##, diagnostics: PenDiagnosticCollector? = nil) throws -> EmitResult {
        let json = ##"{"version": "2.17", "themes": \##(themes), "variables": \##(variables), "children": [\##(children)]}"##
        let document = try PenParser.parse(Data(json.utf8))
        return try SwiftUIEmitter.emit(
            document: document, components: ComponentAnalyzer.analyze(document), pages: PageAnalyzer.analyze(document),
            theme: ThemeAnalyzer.analyze(document), diagnostics: diagnostics
        )
    }

    @Test("Every view that reads the theme declares it, a control's state faces included", arguments: [
        "woodcase-app", "codegen-states", "banking",
    ])
    func everyReadIsDeclared(fixture: String) throws {
        let views = try SwiftUIFixtures.emit(fixture).files.filter {
            $0.path.contains("/Components/") || $0.path.contains("/Pages/")
        }
        for view in views where view.content.contains("theme.") {
            // A read inside a `PenThemeReader { theme in … }` is the reader's own parameter.
            let declared = view.content.contains("@Environment(\\.penTheme) private var theme")
            let readerOnly = view.content.contains("PenThemeReader") && !declared
            #expect(declared || readerOnly, "\(view.path) reads the theme without declaring it")
        }
    }

    private static func files(_ result: EmitResult) -> [String: String] {
        Dictionary(result.files.map { ($0.path, $0.content) }) { first, _ in first }
    }

    private static func theme(_ result: EmitResult) throws -> String {
        try #require(files(result)[themePath])
    }

    private static func environment(_ result: EmitResult) throws -> String {
        try #require(files(result)[environmentPath])
    }
}
