//
//  SwiftUIEmitterComponentTests.swift
//  WoodcaseTests
//

import Foundation
import Testing
@testable import Woodcase

/// What a reusable component and an instance of one become in emitted SwiftUI, over
/// small synthetic documents: the view struct, its typed props, and the call or inlined
/// copy each `ref` becomes. The fixture goldens (``SwiftUIEmitterComponentGoldenTests``)
/// pin whole files.
struct SwiftUIEmitterComponentTests {
    // MARK: - The component file

    @Test("A component is a public view struct under Components/, with a header and a preview")
    func componentFile() throws {
        let emitted = try emit([card])
        let file = try #require(emitted.files["Sources/PenUI/Components/Card.swift"])
        #expect(file.hasPrefix("//\n//  Card.swift\n//  Generated by Woodcase from the \"Card\" component. Do not edit.\n//\n\nimport SwiftUI\n"))
        #expect(file.contains("public struct Card: View {"))
        #expect(file.contains("    public var body: some View {"))
        #expect(file.contains("#Preview {\n    Card()\n}"))
        #expect(!emitted.diagnostics.contains { $0.message.contains("does not emit components") })
    }

    @Test("A text prop is a String let, defaulted to the text, and the Text reads it")
    func textProp() throws {
        let file = try #require(try emit([card]).files["Sources/PenUI/Components/Card.swift"])
        #expect(file.contains("    public let label: String\n"))
        #expect(file.contains("    public init(label: String = \"Total\") {\n        self.label = label\n    }"))
        #expect(file.contains("Text(label)"))
        #expect(!file.contains("Text(\"Total\")"))
    }

    @Test("A component without props has an empty public init")
    func noProps() throws {
        let plain = ##"{"type": "frame", "id": "P", "name": "Plain", "reusable": true, "width": 10, "height": 10, "fill": "#FF0000"}"##
        let file = try #require(try emit([plain]).files["Sources/PenUI/Components/Plain.swift"])
        #expect(file.contains("    public init() {}"))
    }

    @Test("A colour prop is a Color defaulted to the fill, and the shape fills with it")
    func colourProp() throws {
        let file = try #require(try emit([swatch]).files["Sources/PenUI/Components/Swatch.swift"])
        #expect(file.contains("    public let tint: Color\n"))
        #expect(file.contains("public init(tint: Color = Color(hex: 0xFF0000))"))
        #expect(file.contains(".fill(tint)"))
    }

    @Test("An image prop is an Image defaulted to the bundled file, and the fill draws it")
    func imageProp() throws {
        let file = try #require(try emit([photo]).files["Sources/PenUI/Components/Photo.swift"])
        #expect(file.contains("    public let image: Image\n"))
        // `Bundle.module` is internal, and a public init's default may not name it, so the
        // default is applied in the init's body.
        #expect(file.contains("public init(image: Image? = nil)"))
        #expect(file.contains("self.image = image ?? Image(penResource: \"a.png\", bundle: .module)"))
        #expect(file.contains(/\n\s+image\n\s+\.resizable\(\)\n\s+\.scaledToFill\(\)/))
        #expect(!file.contains("Image(penResource: \"a.png\", bundle: .module)\n                .resizable()"))
    }

    @Test("A prop whose node SwiftUI cannot bind is left out, with a warning")
    func unbindableProp() throws {
        let box = ##"""
        {"type": "frame", "id": "B", "name": "Box", "reusable": true, "metadata": {"_props": {"stars": "Stars"}},
         "children": [{"type": "frame", "id": "S", "name": "Stars", "width": 10, "height": 10}]}
        """##
        let emitted = try emit([box])
        let file = try #require(emitted.files["Sources/PenUI/Components/Box.swift"])
        #expect(!file.contains("stars"))
        #expect(emitted.diagnostics.contains { $0.nodeID == "B" && $0.message.contains("stars") })
    }

    @Test("A component named like a SwiftUI type is suffixed View, and so are its calls")
    func shadowedName() throws {
        let toggle = ##"{"type": "frame", "id": "T", "name": "Toggle", "reusable": true, "width": 44, "height": 26, "fill": "#00FF00"}"##
        let page = page(##"{"type": "ref", "id": "i", "ref": "T"}"##)
        let emitted = try emit([toggle, page])
        #expect(emitted.files["Sources/PenUI/Components/ToggleView.swift"]?.contains("public struct ToggleView: View {") == true)
        #expect(emitted.files["Sources/PenUI/Pages/Board.swift"]?.contains("ToggleView()") == true)
    }

    @Test("A page named like a component is suffixed Page")
    func pageNamedLikeAComponent() throws {
        let clash = ##"{"type": "frame", "id": "C2", "name": "Card", "width": 10, "height": 10}"##
        let emitted = try emit([card, clash])
        #expect(emitted.files["Sources/PenUI/Components/Card.swift"] != nil)
        #expect(emitted.files["Sources/PenUI/Pages/CardPage.swift"]?.contains("public struct CardPage: View {") == true)
    }

    // MARK: - Instances

    @Test("A ref with no overrides is a call with no arguments")
    func bareInstance() throws {
        let code = try pageSource([card], instance: ##"{"type": "ref", "id": "i", "ref": "K"}"##)
        #expect(code.contains("            Card()\n"))
    }

    @Test("A ref whose overrides all map to props passes them as arguments")
    func mappedInstance() throws {
        let code = try pageSource([card], instance: ##"{"type": "ref", "id": "i", "ref": "K", "descendants": {"L": {"content": "Revenue"}}}"##)
        #expect(code.contains("Card(label: \"Revenue\")"))
    }

    @Test("An override equal to the prop's default passes nothing")
    func defaultValuedOverride() throws {
        let code = try pageSource([card], instance: ##"{"type": "ref", "id": "i", "ref": "K", "descendants": {"L": {"content": "Total"}}}"##)
        #expect(code.contains("Card()"))
    }

    @Test("A colour and an image override are Swift values in the call; the image is bundled")
    func typedArguments() throws {
        let emitted = try emit([swatch, photo, page(##"""
        {"type": "ref", "id": "i", "ref": "W", "descendants": {"D": {"fill": "#00FF00"}}},
        {"type": "ref", "id": "j", "ref": "F", "descendants": {"G": {"fill": {"type": "image", "url": "./b.png", "mode": "fill"}}}}
        """##)])
        let code = try #require(emitted.files["Sources/PenUI/Pages/Board.swift"])
        #expect(code.contains("Swatch(tint: Color(hex: 0x00FF00))"))
        #expect(code.contains("Photo(image: Image(penResource: \"b.png\", bundle: .module))"))
        #expect(emitted.result.imageAssetURLs == ["./a.png", "./b.png"])
    }

    @Test("Overrides that change nothing — x and y in a stack, a value equal to the node's — keep the call")
    func noOpOverrides() throws {
        let code = try pageSource([card], instance: ##"""
        {"type": "ref", "id": "i", "ref": "K", "descendants": {"L": {"content": "Revenue", "x": 12, "y": 4, "fontSize": 12}, "Y": {"height": 64}}}
        """##)
        #expect(code.contains("Card(label: \"Revenue\")"))
    }

    @Test("An override no prop carries inlines the patched component, with a comment and a warning")
    func unmappedInstance() throws {
        let emitted = try emit([card, page(##"{"type": "ref", "id": "i", "ref": "K", "descendants": {"L": {"fontSize": 20}}}"##)])
        let code = try #require(emitted.files["Sources/PenUI/Pages/Board.swift"])
        #expect(!code.contains("Card("))
        #expect(code.contains("// woodcase: inlined from Card"))
        #expect(code.contains(".penFont(size: 20)"))
        #expect(code.contains("Text(\"Total\")"))
        #expect(emitted.diagnostics.contains { $0.nodeID == "i" && $0.message.contains("Card") && $0.message.contains("L") })
    }

    @Test("A root override that changes the component's size inlines it; one that does not keeps the call")
    func rootSizeOverride() throws {
        let resized = try pageSource([card], instance: ##"{"type": "ref", "id": "i", "ref": "K", "width": 200}"##)
        #expect(!resized.contains("Card("))
        #expect(resized.contains(".frame(width: 200, height: 80"))
        let same = try pageSource([card], instance: ##"{"type": "ref", "id": "i", "ref": "K", "width": 140}"##)
        #expect(same.contains("Card()"))
    }

    @Test("A rotated instance is inlined, because its turn needs the component's box")
    func rotatedInstance() throws {
        let code = try pageSource([card], instance: ##"{"type": "ref", "id": "i", "ref": "K", "rotation": 90}"##)
        #expect(!code.contains("Card("))
        #expect(code.contains(".rotationEffect(.degrees(-90))"))
    }

    @Test("An instance keeps its own placement: offset in a ZStack, and opacity")
    func instancePlacement() throws {
        let json = page(##"{"type": "ref", "id": "i", "ref": "K", "x": 5, "y": 6, "opacity": 0.5}"##, layout: "none")
        let code = try #require(try emit([card, json]).files["Sources/PenUI/Pages/Board.swift"])
        #expect(code.contains("Card()\n                .offset(x: 5, y: 6)\n                .opacity(0.5)"))
    }

    @Test("A component that uses another calls it")
    func nestedInstance() throws {
        let shelf = ##"{"type": "frame", "id": "H", "name": "Shelf", "reusable": true, "children": [{"type": "ref", "id": "n", "ref": "K"}]}"##
        let file = try #require(try emit([card, shelf]).files["Sources/PenUI/Components/Shelf.swift"])
        #expect(file.contains("Card()"))
    }

    @Test("A ref to a reusable node that is no analyzed component is inlined")
    func unanalyzedTarget() throws {
        let variant = ##"{"type": "frame", "id": "V", "name": "Card:hot", "reusable": true, "width": 10, "height": 10, "fill": "#FF0000"}"##
        let code = try pageSource([card, variant], instance: ##"{"type": "ref", "id": "i", "ref": "V"}"##, components: { $0.filter { $0.id != "V" } })
        #expect(code.contains("// woodcase: inlined from"))
        #expect(code.contains("Color(hex: 0xFF0000)"))
    }

    @Test("A ref to nothing is a placeholder with a warning")
    func danglingRef() throws {
        let emitted = try emit([page(##"{"type": "ref", "id": "i", "ref": "nope", "width": 10, "height": 10}"##)])
        let code = try #require(emitted.files["Sources/PenUI/Pages/Board.swift"])
        #expect(code.contains("Color.clear"))
        #expect(emitted.diagnostics.contains { $0.nodeID == "i" && $0.message.contains("nope") })
    }

    @Test("A slot the instance fills is drawn with the instance's content, inlined")
    func filledSlot() throws {
        let holder = ##"""
        {"type": "frame", "id": "O", "name": "Holder", "reusable": true, "layout": "vertical",
         "children": [{"type": "frame", "id": "S", "name": "Slot", "slot": ["text"], "layout": "vertical"}]}
        """##
        let code = try pageSource([holder], instance: ##"""
        {"type": "ref", "id": "i", "ref": "O", "descendants": {"S": {"children": [{"type": "text", "id": "t", "content": "Filled"}]}}}
        """##)
        #expect(code.contains("Text(\"Filled\")"))
    }

    // MARK: - Resources

    @Test("Images and icons a component draws are in the result")
    func componentResources() throws {
        let icon = ##"""
        {"type": "frame", "id": "I", "name": "Iconic", "reusable": true,
         "children": [{"type": "icon", "id": "c", "library": "lucide", "icon": "heart", "width": 16, "height": 16, "fill": "#000000"}]}
        """##
        let emitted = try emit([photo, icon])
        #expect(emitted.result.imageAssetURLs == ["./a.png"])
        #expect(emitted.result.iconLibraries == ["lucide"])
    }

    // MARK: - Helpers

    /// A card whose `label` prop reads its text, the shape of `pages.pen`'s.
    private let card = ##"""
    {"type": "frame", "id": "K", "name": "Card", "reusable": true, "width": 140, "height": 80, "layout": "vertical",
     "metadata": {"type": "component", "_props": {"label": "Body/Label"}},
     "children": [{"type": "frame", "id": "Y", "name": "Body", "layout": "vertical", "width": 124, "height": 64,
                   "children": [{"type": "text", "id": "L", "name": "Label", "content": "Total", "fontSize": 12}]}]}
    """##

    /// A swatch whose `tint` prop reads a rectangle's colour.
    private let swatch = ##"""
    {"type": "frame", "id": "W", "name": "Swatch", "reusable": true, "metadata": {"_props": {"tint": "Dot"}},
     "children": [{"type": "rectangle", "id": "D", "name": "Dot", "width": 10, "height": 10, "fill": "#FF0000"}]}
    """##

    /// A photo whose `image` prop reads a frame's image fill.
    private let photo = ##"""
    {"type": "frame", "id": "F", "name": "Photo", "reusable": true, "metadata": {"_props": {"image": "Pic"}},
     "children": [{"type": "frame", "id": "G", "name": "Pic", "width": 40, "height": 40, "clip": true,
                   "fill": {"type": "image", "url": "./a.png", "mode": "fill"}}]}
    """##

    /// A page frame named Board holding `children` (comma-separated node objects).
    private func page(_ children: String, layout: String = "horizontal") -> String {
        ##"{"type": "frame", "id": "root", "name": "Board", "layout": "\##(layout)", "width": 400, "height": 300, "children": [\##(children)]}"##
    }

    /// The emitted page of a document holding `nodes` and a Board page around `instance`.
    private func pageSource(
        _ nodes: [String], instance: String,
        components filter: ([ComponentDefinition]) -> [ComponentDefinition] = { $0 }
    ) throws -> String {
        let emitted = try emit(nodes + [page(instance)], components: filter)
        return try #require(emitted.files["Sources/PenUI/Pages/Board.swift"])
    }

    /// Emit a document whose top-level nodes are `nodes`, the way `woodcase generate swiftui` does.
    private func emit(
        _ nodes: [String],
        components filter: ([ComponentDefinition]) -> [ComponentDefinition] = { $0 }
    ) throws -> (files: [String: String], result: EmitResult, diagnostics: [PenDiagnostic]) {
        let json = ##"{"version": "2.17", "children": [\##(nodes.joined(separator: ", "))]}"##
        let document = try PenParser.parse(Data(json.utf8))
        let diagnostics = PenDiagnosticCollector()
        let result = SwiftUIEmitter.emit(
            document: document, components: filter(ComponentAnalyzer.analyze(document)),
            pages: PageAnalyzer.analyze(document), theme: ThemeAnalyzer.analyze(document), diagnostics: diagnostics
        )
        let files = Dictionary(result.files.map { ($0.path, $0.content) }) { first, _ in first }
        return (files, result, diagnostics.diagnostics)
    }
}
