//
//  SwiftUIEmitter+Package.swift
//  Woodcase
//

import Foundation

extension SwiftUIEmitter {
    /// The emitted `Support/` files, keyed by file name: every `.swift` file in the bundled
    /// `CodeGen/SwiftUITemplates/` directory, verbatim.
    ///
    /// `PenSupport.swift` is the core; each concern the views need beyond SwiftUI adds its own
    /// `PenSupport+<Concern>.swift` beside it. These are the only files that may branch on
    /// `#available`, so a lower deployment floor costs no change anywhere else.
    ///
    /// - Returns: The templates, read once per process.
    /// - Throws: ``WoodcaseResources/Missing`` when the resource bundle cannot be found.
    static func supportTemplates() throws -> [String: String] {
        try loadedSupportTemplates.get()
    }

    private static let loadedSupportTemplates: Result<[String: String], WoodcaseResources.Missing> = Result {
        try readSupportTemplates(from: WoodcaseResources.bundle())
    }.mapError { $0 as? WoodcaseResources.Missing ?? WoodcaseResources.Missing(searched: []) }

    private static func readSupportTemplates(from bundle: Bundle) -> [String: String] {
        let urls = bundle.urls(forResourcesWithExtension: "swift", subdirectory: "SwiftUITemplates") ?? []
        var templates: [String: String] = [:]
        for url in urls {
            guard let content = try? String(contentsOf: url, encoding: .utf8) else {
                preconditionFailure("Could not read SwiftUI template: \(url.lastPathComponent)")
            }
            templates[url.lastPathComponent] = content
        }
        guard templates["PenSupport.swift"] != nil else {
            preconditionFailure("Missing SwiftUI template: PenSupport.swift")
        }
        return templates
    }

    /// A minimal `Package.swift`: one library of the module, which processes
    /// `Resources/`, and the `<module>Catalog` executable that opens its catalog, on the
    /// floor's platforms.
    ///
    /// Regenerated on every run, like every other file the emitter writes: its content is
    /// a function of the module name and the floor alone, so a run with a new `--floor` or
    /// a document that gains its first image or font never leaves it stale. It always
    /// declares `resources: [.process("Resources")]` — which is what gives the module
    /// `Bundle.module`, and the support file's `PenFonts` reads it — whether or not the
    /// document bundles anything, because ``resourcesPlaceholder(module:)`` keeps the
    /// directory in existence. A person extends a package of their own that depends on
    /// this one, never this manifest.
    static func manifest(options: Options) -> GeneratedFile {
        let name = options.moduleName
        let floor = options.deploymentFloor
        let content = """
        // swift-tools-version: 6.2
        // Generated by Woodcase from a .pen file, and rewritten by every run of
        // `woodcase generate swiftui`. Do not edit: depend on this package from your own.

        import PackageDescription

        let package = Package(
            name: "\(name)",
            platforms: [
                .iOS("\(floor.iOSVersion)"),
                .macOS("\(floor.macOSVersion)"),
            ],
            products: [
                .library(name: "\(name)", targets: ["\(name)"]),
                .executable(name: "\(name)Catalog", targets: ["\(name)Catalog"]),
            ],
            targets: [
                .target(name: "\(name)", resources: [.process("Resources")]),
                .executableTarget(name: "\(name)Catalog", dependencies: ["\(name)"]),
            ]
        )

        """
        return GeneratedFile(path: "Package.swift", content: content)
    }

    /// An empty `Sources/<module>/Resources/.gitkeep`: SwiftPM refuses a declared resource
    /// directory that does not exist, and version control drops an empty one, so a
    /// package whose document bundles nothing still builds after a clone. SwiftPM leaves
    /// the hidden file out of the bundle.
    static func resourcesPlaceholder(module: String) -> GeneratedFile {
        GeneratedFile(path: "Sources/\(module)/Resources/.gitkeep", content: "")
    }
}
