//
//  SwiftUITheme+Source.swift
//  Woodcase
//

extension SwiftUITheme {
    /// `PenTheme.swift`: the struct, an enum per axis, a stored property per axis defaulting
    /// to its first option as Pen's default theme does, and a computed property per variable
    /// that switches on the axes its value depends on.
    var themeSource: String {
        var lines = Self.header("PenTheme", source: "the document's themes and variables")
        lines += [
            "/// The document's theme: an option on each of its axes, and its variables as they read under them.",
            "///",
            "/// Views read it from the environment (`@Environment(\\.penTheme)`); `penTheme(…)` sets it on a subtree.",
            "public struct PenTheme: Hashable, Sendable {",
        ]
        for axis in axes {
            let bridge = axis.bridgesColorScheme ? ", which follows the color scheme" : ""
            lines.append("    /// The `\(axis.name)` axis\(bridge).")
            lines.append("    public enum \(axis.typeName): String, CaseIterable, Hashable, Sendable {")
            for option in axis.options {
                let bare = option.caseName.filter { $0 != "`" }
                let raw = bare == option.value ? "" : " = \(SwiftUILiteral.string(option.value))"
                lines.append("        case \(option.caseName)\(raw)")
            }
            lines += ["    }", ""]
        }
        for axis in axes {
            lines.append("    /// The option on the `\(axis.name)` axis.")
            lines.append("    public var \(axis.property): \(axis.typeName)")
        }
        if !axes.isEmpty {
            lines.append("")
        }
        lines.append("    /// A theme; each axis defaults to its first option, as Pen's default theme does.")
        let parameters = axes.map { "\($0.property): \($0.typeName) = \($0.options.first?.member ?? ".init()")" }
        if axes.isEmpty {
            lines.append("    public init() {}")
        } else {
            lines.append("    public init(\(parameters.joined(separator: ", "))) {")
            lines += axes.map { "        self.\($0.property) = \($0.property)" }
            lines.append("    }")
        }
        lines.append("}")
        let tokens = sortedTokens
        if !tokens.isEmpty {
            lines += ["", "public extension PenTheme {"]
            for (index, token) in tokens.enumerated() {
                if index > 0 { lines.append("") }
                lines += tokenLines(token)
            }
            lines.append("}")
        }
        return lines.joined(separator: "\n") + "\n"
    }

    /// One variable's computed property.
    private func tokenLines(_ token: Token) -> [String] {
        var lines = [
            "    /// `$\(token.variable)`.",
            "    var \(token.property): \(token.swiftType) {",
        ]
        if token.axes.isEmpty {
            lines.append("        \(token.cases.first?.code ?? "")")
        } else {
            let subjects = token.axes.map { axes[$0].property }
            let subject = subjects.count == 1 ? subjects[0] : "(\(subjects.joined(separator: ", ")))"
            lines.append("        switch \(subject) {")
            for value in token.cases {
                let members = zip(token.axes, value.options).map { axes[$0].options[$1].member }
                let pattern = members.count == 1 ? members[0] : "(\(members.joined(separator: ", ")))"
                lines.append("        case \(pattern): \(value.code)")
            }
            lines.append("        }")
        }
        lines.append("    }")
        return lines
    }

    /// A generated file's opening comment and import.
    static func header(_ name: String, source: String) -> [String] {
        [
            "//",
            "//  \(name).swift",
            "//  Generated by Woodcase from \(source). Do not edit.",
            "//",
            "",
            "import SwiftUI",
            "",
        ]
    }
}
