//
//  SwiftUICatalog+Executable.swift
//  Woodcase
//

extension SwiftUICatalog {
    /// The `<module>Catalog` executable's `main.swift`: on macOS, the catalog in a window —
    /// `swift run <module>Catalog`, no Xcode project — or, given `--snapshot <path>`, the
    /// sheet under every theme rendered to a PNG at 2x, less where 2x would pass the largest
    /// bitmap `ImageRenderer` draws (16,384 pixels a side, measured on `woodcase-app`), or,
    /// given `--fonts`, one line per bundled font file — `registered` or `failed`, its
    /// family, its file — exiting 1 when Core Text refused one.
    ///
    /// A bare executable is not an app bundle, so it asks for a regular activation policy
    /// to get a Dock icon and a key window. Elsewhere it does nothing: an iOS app needs a
    /// bundle, and the catalog is there as `PenCatalog` for one to show.
    func mainSource(module: String) -> String {
        let app = "\(module)CatalogApp"
        let lines = [
            "//",
            "//  main.swift",
            "//  Generated by Woodcase from the document's components, pages and theme. Do not edit.",
            "//",
            "//  `swift run \(module)Catalog` opens the catalog in a window;",
            "//  `swift run \(module)Catalog --snapshot catalog.png` renders it under every theme instead;",
            "//  `swift run \(module)Catalog --fonts` lists the fonts the package bundles and whether each registered.",
            "//",
            "",
            "#if os(macOS)",
            "    import AppKit",
            "    import \(module)",
            "    import SwiftUI",
            "    import UniformTypeIdentifiers",
            "",
            "    /// The catalog in a window.",
            "    struct \(app): App {",
            "        var body: some Scene {",
            "            WindowGroup(\(SwiftUILiteral.string(module))) {",
            "                PenCatalog()",
            "                    .frame(minWidth: 640, minHeight: 480)",
            "            }",
            "        }",
            "    }",
            "",
            "    let arguments = CommandLine.arguments",
            "    if arguments.contains(\"--fonts\") {",
            "        // Each bundled font file, its family and whether Core Text took it; any refusal exits 1.",
            "        for face in PenFonts.faces {",
            "            print(\"\\(face.isRegistered ? \"registered\" : \"failed\")\\t\\(face.family)\\t\\(face.file)\")",
            "        }",
            "        exit(PenFonts.faces.allSatisfy(\\.isRegistered) ? 0 : 1)",
            "    } else if let flag = arguments.firstIndex(of: \"--snapshot\") {",
            "        // The sheet under every theme, at 2x or as near it as keeps the bitmap under the",
            "        // 16,384 pixels a side ImageRenderer draws.",
            "        let path = arguments.indices.contains(flag + 1) ? arguments[flag + 1] : \"catalog.png\"",
            "        let renderer = ImageRenderer(content: PenCatalogThemes())",
            "        if let probe = renderer.cgImage {",
            "            renderer.scale = min(2, 16000 / CGFloat(max(probe.width, probe.height)))",
            "        }",
            "        let url = URL(filePath: path) as CFURL",
            "        guard let image = renderer.cgImage,",
            "              let destination = CGImageDestinationCreateWithURL(url, UTType.png.identifier as CFString, 1, nil)",
            "        else {",
            "            try? FileHandle.standardError.write(contentsOf: Data(\"Could not render the catalog to \\(path)\\n\".utf8))",
            "            exit(1)",
            "        }",
            "        CGImageDestinationAddImage(destination, image, nil)",
            "        guard CGImageDestinationFinalize(destination) else {",
            "            try? FileHandle.standardError.write(contentsOf: Data(\"Could not write \\(path)\\n\".utf8))",
            "            exit(1)",
            "        }",
            "        print(\"Wrote \\(path)\")",
            "    } else {",
            "        NSApplication.shared.setActivationPolicy(.regular)",
            "        NSApplication.shared.activate()",
            "        \(app).main()",
            "    }",
            "#endif",
        ]
        return lines.joined(separator: "\n") + "\n"
    }
}
