#!/usr/bin/env python3
"""
Generate Swift codepoint dictionaries from icon font metadata.

Reads codepoint data from various sources (JSON, CSS, codepoint files)
and outputs Swift files with compiled-in dictionaries for each icon font family.

Usage:
    python3 scripts/generate-icon-codepoints.py

Requires:
    - lucide info.json (from lucide-static npm package)
    - phosphor regular/style.css (from @phosphor-icons/web npm package)
    - feather iconfont.css (from AT-UI/feather-font GitHub)
    - Material Symbols codepoints file (from Google GitHub)
"""

import json
import re
import sys
from pathlib import Path

OUTPUT_DIR = Path(__file__).parent.parent / "Sources" / "Woodcase" / "IconFonts"


def parse_lucide(info_json_path: str) -> dict[str, int]:
    """Parse lucide info.json: { "icon-name": { "encodedCode": "\\eXXX" } }"""
    with open(info_json_path) as f:
        data = json.load(f)
    mapping = {}
    for name, info in data.items():
        encoded = info.get("encodedCode", "")
        # Format: \eXXX
        if encoded.startswith("\\"):
            codepoint = int(encoded[1:], 16)
            mapping[name] = codepoint
    return mapping


def parse_phosphor_css(css_path: str) -> dict[str, int]:
    """Parse phosphor CSS in either v1 or v2 format.

    v1: .ph-icon-name::before { content: "\\fXXX"; }
    v2: .ph.ph-icon-name:before { content: "\\eXXX"; }
    """
    with open(css_path) as f:
        css = f.read()
    mapping = {}
    # Match both v1 (.ph-name::before) and v2 (.ph.ph-name:before) formats
    pattern = re.compile(
        r'\.ph(?:\.ph)?-([\w-]+)::?before\s*\{\s*content:\s*"\\([0-9a-fA-F]+)"',
    )
    for match in pattern.finditer(css):
        name = match.group(1)
        codepoint = int(match.group(2), 16)
        mapping[name] = codepoint
    return mapping


def parse_feather_css(css_path: str) -> dict[str, int]:
    """Parse feather iconfont.css: .icon-name:before {content: "\\eXXX";}"""
    with open(css_path) as f:
        css = f.read()
    mapping = {}
    # Match: .icon-name:before {content: "\eXXX";}
    pattern = re.compile(
        r'\.icon-([\w-]+):before\s*\{content:\s*"\\([0-9a-fA-F]+)";\}',
    )
    for match in pattern.finditer(css):
        name = match.group(1)
        codepoint = int(match.group(2), 16)
        mapping[name] = codepoint
    return mapping


def parse_material_codepoints(codepoints_path: str) -> dict[str, int]:
    """Parse Google Material Symbols codepoints file: name hex_codepoint"""
    mapping = {}
    with open(codepoints_path) as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) == 2:
                name = parts[0]
                codepoint = int(parts[1], 16)
                mapping[name] = codepoint
    return mapping


def write_swift_file(
    filename: str, dict_name: str, mapping: dict[str, int], doc_comment: str
):
    """Write a Swift file with a static dictionary of icon name -> codepoint."""
    output_path = OUTPUT_DIR / filename
    lines = []
    lines.append("//")
    lines.append(f"//  {filename}")
    lines.append("//  Woodcase")
    lines.append("//")
    lines.append(f"//  Auto-generated by scripts/generate-icon-codepoints.py")
    lines.append("//")
    lines.append("")
    lines.append(f"/// {doc_comment}")
    lines.append(f"enum {dict_name} {{")
    lines.append(f"    static let codepoints: [String: UInt32] = [")

    for name in sorted(mapping.keys()):
        codepoint = mapping[name]
        lines.append(f'        "{name}": 0x{codepoint:04X},')

    lines.append("    ]")
    lines.append("}")
    lines.append("")

    output_path.write_text("\n".join(lines))
    print(f"  Wrote {filename}: {len(mapping)} entries")


def main():
    print("Generating icon codepoint dictionaries...")

    # Lucide (v0.563.0 — matches Pencil's bundled version)
    lucide_info = "/tmp/pencil-versions/font/info.json"
    try:
        lucide = parse_lucide(lucide_info)
        write_swift_file(
            "LucideCodepoints.swift",
            "LucideCodepoints",
            lucide,
            "Codepoint mappings for the Lucide icon font (~1952 icons).",
        )
    except FileNotFoundError:
        print(f"  SKIP lucide: {lucide_info} not found")

    # Phosphor (v1.4.2 — matches Pencil's bundled version; all weights in one font)
    phosphor_css = "/tmp/pencil-versions/package/src/css/icons.css"
    try:
        phosphor = parse_phosphor_css(phosphor_css)
        write_swift_file(
            "PhosphorCodepoints.swift",
            "PhosphorCodepoints",
            phosphor,
            "Codepoint mappings for the Phosphor icon font (regular weight).",
        )
    except FileNotFoundError:
        print(f"  SKIP phosphor: {phosphor_css} not found")

    # Feather
    feather_css = "/tmp/feather-iconfont.css"
    try:
        feather = parse_feather_css(feather_css)
        write_swift_file(
            "FeatherCodepoints.swift",
            "FeatherCodepoints",
            feather,
            "Codepoint mappings for the Feather icon font.",
        )
    except FileNotFoundError:
        print(f"  SKIP feather: {feather_css} not found")

    # Material Symbols (shared by Outlined, Rounded, Sharp)
    material_codepoints = "/tmp/material-symbols-outlined.codepoints"
    try:
        material = parse_material_codepoints(material_codepoints)
        write_swift_file(
            "MaterialSymbolsCodepoints.swift",
            "MaterialSymbolsCodepoints",
            material,
            "Codepoint mappings for Material Symbols (shared by Outlined, Rounded, and Sharp variants).",
        )
    except FileNotFoundError:
        print(f"  SKIP material: {material_codepoints} not found")

    print("Done!")


if __name__ == "__main__":
    main()
